Azure/azure-functions-templates

Templates/BlobTrigger-CSharp/run.csx, Templates/Empty-CSharp/run.csx, Templates/HttpTrigger-CSharp/run.csx, Templates/QueueTrigger-CSharp/run.csx, Templates/TimerTrigger-CSharp/run.csx, Templates/WebHook-Generic-CSharp/run.csx
The removed namespaces are automatically added by the C# function compilation process. Removing from the templates to reduce the amount of code and bring the function (relevant) code up.
=> Removing redundant C# namespace imports

Bindings/bindings.json, Templates/BlobTrigger-CSharp/function.json, Templates/BlobTrigger-CSharp/metadata.json, Templates/BlobTrigger-NodeJS/function.json, Templates/BlobTrigger-NodeJS/metadata.json, Templates/EventHubTrigger-NodeJS/function.json, Templates/EventHubTrigger-NodeJS/metadata.json, Templates/QueueTrigger-Bash/function.json, Templates/QueueTrigger-Bash/metadata.json, Templates/QueueTrigger-Batch/function.json, Templates/QueueTrigger-Batch/metadata.json, Templates/QueueTrigger-CSharp/function.json, Templates/QueueTrigger-CSharp/metadata.json, Templates/QueueTrigger-FSharp/function.json, Templates/QueueTrigger-FSharp/metadata.json, Templates/QueueTrigger-NodeJS/function.json, Templates/QueueTrigger-NodeJS/metadata.json, Templates/QueueTrigger-Php/function.json, Templates/QueueTrigger-Php/metadata.json, Templates/QueueTrigger-Powershell/function.json, Templates/QueueTrigger-Powershell/metadata.json, Templates/QueueTrigger-Python/function.json, Templates/QueueTrigger-Python/metadata.json
See the script PR https://github.com/Azure/azure-webjobs-sdk-script/pull/128 for details.
Basically we've made the "connection string" metadata property consistent across the bindings.
=> Absorbing connectionString/storageAccount metadata name changes

Bindings/bindings.json, Templates/ServiceBusQueueTrigger-NodeJS/metadata.json
We missed this one when I did the renames in https://github.com/Azure/azure-webjobs-sdk-templates/commit/c5cd105875b09e0ea7ec3d0d17df4e34c984fa14.
=> Fixing ServiceBus template name + Generic JSON WebHook binding

Bindings/bindings.json
fixing the trigger regex to allow container + blob name as well as only blob name
Fixed the input and output regex to allow only one consecutive - in the container name
=> Fixed the regex for blob binding

LICENSE.txt, README.md
Putting the same license + readme pointer that we use for our other repos (e.g. https://github.com/Azure/azure-webjobs-sdk)
=> Adding Licence.txt and Readme pointer

Bindings/bindings.json
Support for EH consumer group is going out in the upcoming release, so we need to expose this.
=> Adding Consumer Group to the EventHub binding

Bindings/bindings.json
Add FTP and SFTP to ApiHubFile triggers and remove Azure Blob from list of triggers
=> Add FTP and SFTP to ApiHubFile triggers and remove Azure Blob 

Templates/Empty-FSharp/run.fsx, Templates/QueueTrigger-CSharp/readme.md, Templates/QueueTrigger-FSharp/readme.md, Templates/QueueTrigger-FSharp/run.fsx, Templates/QueueTrigger-FSharp/sample.dat
Updating existing F# samples to work with the new F# language model.
**NOTE**: This will only work with the next release (runtime version 0.5.x +) and should not be pushed before that is available.
=> Updating F# templates to work with new model

Documentation/tableIn.md, Documentation/tableOut.md
marked ignores the trailing `#`. I tried escaping with `\` but that didn't work. 
A trailing `&nbsp;` is an option , where we get to keep the text as is, but I don't know how it'll look like in parsers.
=> Changing text to remove the trailing # in C#

Resources/Resources.resx, Resources/cs-CZ/Resources/Resources.resx, Resources/de-DE/Resources/Resources.resx, Resources/es-ES/Resources/Resources.resx, Resources/fr-FR/Resources/Resources.resx, Resources/hu-HU/Resources/Resources.resx, Resources/it-IT/Resources/Resources.resx, Resources/ja-JP/Resources/Resources.resx, Resources/ko-KR/Resources/Resources.resx, Resources/nl-NL/Resources/Resources.resx, Resources/pl-PL/Resources/Resources.resx, Resources/pt-BR/Resources/Resources.resx, Resources/pt-PT/Resources/Resources.resx, Resources/ru-RU/Resources/Resources.resx, Resources/sv-SE/Resources/Resources.resx, Resources/tr-TR/Resources/Resources.resx, Resources/zh-CN/Resources/Resources.resx, Resources/zh-TW/Resources/Resources.resx
Updating Twilio binding settings descriptions to make it clear that app settings should be used for Account SID and Auth Token
=> Updating Twilio binding settings descriptions

Templates/ImageResizer-CSharp/run.csx
Since automatic NuGet restore now works, remove the commented out code that used System.Drawing. Also cleaned up "using" statements that weren't needed.
=> Update ImageResizer sample, remove System.Drawing

Bindings/bindings.json
Notification Hub name is a required value and customers might miss configuring this value if there is a default value.
=> Remove default value for Notification Hub name

Bindings/bindings.json
Event Hubs and Service Bus entities (event hubs, consumer groups, topics, subscriptions, queues) have the same validation rules. This PR fixes some issues with the validation and uses the same regex for Event Hubs and Service Bus.
- Upper case letters are allowed
- 1 and 2 character entity names are allowed (currently Service Bus validation does not allow this)
Corresponding validation messages (and translations) may need to be updated.
=> Update Event Hubs and Service Bus validation

Templates/SasToken-CSharp/readme.md, Templates/SasToken-CSharp/run.csx
Currently, if your request body is:
```
{
"ContainerName": "someContainer"
}
```
You get _Invalid value for 'permissions'_ response.
This change allows implementation to match to documentation and make **Permissions** _optional_ while defaulting to **Read** if it is not supplied.
@fabiocav 
@soninaren
=> Fix permissions to be optional -- if permission was supplied, check if it is a possible value

Bindings/bindings.json, Documentation/eventHubTrigger.md, Resources/Resources.resx, Templates/EventHubTrigger-JavaScript/function.json, Templates/EventHubTrigger-JavaScript/index.js
@soninaren gonna need you on this one, we need to discuss what lights up in the portal / how much of that we want to do :)
resolves #429
=> Change node event hub cardinality

Functions.Templates/Documentation/cosmosDBTrigger.md, Functions.Templates/Documentation/documentDBIn.md, Functions.Templates/Documentation/documentDBOut.md
For every file:
- Specified that settings can be set both on the portal and in the `function.json` file in the Advanced options.
- Added the portal names next to the parameter names.
- Specified if any of the parameters is not on the Azure portal
=> Updating instructions to include portal parameter names

Functions.Templates/Bindings/bindings.json
Removing azurefile and filesystem from ExternalFile triggers as they are not supported.
=> Removing azurefile and filesystem from ExternalFile triggers

Functions.Templates/Templates/QueueTrigger-Powershell/run.ps1
I've found when I try to ConvertFrom-Json the $in it was failing, the issue was down the to Get-Content requiring -Raw. Might be useful for others if by default this is set
=> Add -Raw to Get-Content

Functions.Templates/Templates/CosmosDBTrigger-CSharp/CosmosDBTriggerCSharp.cs, Functions.Templates/Templates/CosmosDBTrigger-JavaScript/index.js
When a Function is created on Consumption Plan (not Dedicated), the Function gets a first time trigger with an empty list that generates a runtime error on the template.
=> Fixing Cosmos trigger templates for Consumption Plan

Functions.Templates/Documentation/cosmosDBTrigger.md
This change adds documentation for the new attributes present in `function.json`.
Based on the following PRs:
* https://github.com/Azure/azure-webjobs-sdk-script/pull/2306
* https://github.com/Azure/azure-webjobs-sdk-extensions/pull/337
=> New attributes for Cosmos DB Trigger

Functions.Templates/Templates/CosmosDBTrigger-CSharp/CosmosDBTriggerCSharp.cs, Functions.Templates/Templates/CosmosDBTrigger-CSharp/function.json, Functions.Templates/Templates/CosmosDBTrigger-JavaScript/function.json, Functions.Templates/Templates/CosmosDBTrigger-JavaScript/index.js
This PR fixes #576 by renaming the variable that holds the documents that triggered the Function.
=> Renaming Cosmos DB Trigger input parameter to "documents"

Functions.Templates/Templates/GitHubCommenter-CSharp/GitHubCommenterCSharp.cs
When the scheme is set to "Basic", neither of the formats given for the "GITHUB_CREDENTIALS" setting are able to successfully authenticate the account.
I was able to successfully authenticate against GitHub and have the function comment on the issue opened by switching the scheme from "Basic" to "token" (See [this](https://developer.github.com/v3/#oauth2-token-sent-in-a-header) section in the Rest API v3 doc).
=> Change AuthenticationHeaderValue scheme to "token"

Functions.Templates/Templates/HttpTrigger-PowerShell/function.json, Functions.Templates/Templates/HttpTrigger-PowerShell/run.ps1
- `req` and `res` is taken from the C# sample, but for PowerShell scripters, it's better to have the parameter names spelled out
- use `HttpStatusCode` type instead of magic numbers
- consistent formatting of braces
cc @daxian-dbw @tylerl0706
=> fix some style issues

README.md
Updating outdated instructions; project.json has been replaced by sample.dat.
=> Updated project.json to sample.dat in portal-only template instructions step 4.

Functions.Templates/Documentation/eventHubOut.md, Functions.Templates/Documentation/notificationHubOut.md, Functions.Templates/Documentation/timerTrigger.md, Functions.Templates/Templates/TimerTrigger-JavaScript/index.js, Functions.Templates/Templates/TimerTrigger-TypeScript/index.ts
isPastDue should be IsPastDue. In V1, there used to be hard coded logic to make this lower case (https://github.com/Azure/azure-functions-host/blob/2a73a53260b55e8abc61c34da39be04244e5a957/src/WebJobs.Script/Description/Node/NodeFunctionInvoker.cs#L406). In V2, this custom logic doesn't happen.
=> Wrong casing in TimerTrigger JavaScript/Typescript `isPastDue`

FallBackFolderBuild/extensions.json, Functions.Templates/Bindings/bindings.json, Functions.Templates/Templates/DurableFunctionsActivity-CSharp/metadata.json, Functions.Templates/Templates/DurableFunctionsActivity-JavaScript/metadata.json, Functions.Templates/Templates/DurableFunctionsActivity-TypeScript/metadata.json, Functions.Templates/Templates/DurableFunctionsHttpStart-CSharp/metadata.json, Functions.Templates/Templates/DurableFunctionsHttpStart-JavaScript/metadata.json, Functions.Templates/Templates/DurableFunctionsHttpStart-TypeScript/metadata.json, Functions.Templates/Templates/DurableFunctionsOrchestration-CSharp/build.config/template.json, Functions.Templates/Templates/DurableFunctionsOrchestration-CSharp/metadata.json, Functions.Templates/Templates/DurableFunctionsOrchestrator-CSharp/metadata.json, Functions.Templates/Templates/DurableFunctionsOrchestrator-JavaScript/metadata.json, Functions.Templates/Templates/DurableFunctionsOrchestrator-TypeScript/metadata.json
This PR updates all the Durable Functions templates to use the v1.8.0 version of our nuget package:
https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.DurableTask/1.8.0
Related to https://github.com/Azure/azure-functions-durable-extension/issues/580
=> Update durable templates for 1.8.0 nuget package

Functions.Templates/ProjectTemplate/CSharp/build.config/template.json
Currently looks quite ugly when running `dotnet new-l`:
```
Templates                                         Short Name           Language          Tags
------------------------------------------------------------------------------------------------------------------------------
AzureFunctions                                    func                 [C#], F#          Azure Functions/Solution
Console Application                               console              [C#], F#, VB      Common/Console
Class library                                     classlib             [C#], F#, VB      Common/Library
...
```
Same in graphical tools:
=> Project template name looks better with a space

FallBackFolderBuild/extensions.json, Functions.Templates/Bindings/bindings.json, Functions.Templates/Templates/DurableFunctionsActivity-CSharp/metadata.json, Functions.Templates/Templates/DurableFunctionsActivity-JavaScript/metadata.json, Functions.Templates/Templates/DurableFunctionsActivity-TypeScript/metadata.json, Functions.Templates/Templates/DurableFunctionsHttpStart-CSharp/metadata.json, Functions.Templates/Templates/DurableFunctionsHttpStart-JavaScript/metadata.json, Functions.Templates/Templates/DurableFunctionsHttpStart-TypeScript/metadata.json, Functions.Templates/Templates/DurableFunctionsOrchestration-CSharp/build.config/template.json, Functions.Templates/Templates/DurableFunctionsOrchestration-CSharp/metadata.json, Functions.Templates/Templates/DurableFunctionsOrchestrator-CSharp/metadata.json, Functions.Templates/Templates/DurableFunctionsOrchestrator-JavaScript/metadata.json, Functions.Templates/Templates/DurableFunctionsOrchestrator-TypeScript/metadata.json
We recently released Durable Functions [v1.8.2](https://github.com/Azure/azure-functions-durable-extension/releases/tag/v1.8.2). Templates need to be updated to point to this version.
=> Update Durable Functions templates to use v1.8.2

Functions.Templates/ProjectTemplate/CSharp/Company.FunctionApp.csproj, Functions.Templates/ProjectTemplate/FSharp/Company.FunctionApp.fsproj
The DI stuff doesn't work on the current published version of the SDK.  Would be good to update and publish templtes.  I think VS right now pulls down 1.0.26 so lots of people hitting issues with DI azure/azure-functions-host#3736
=> updating nuget version

Functions.Templates/Templates/CosmosDBTrigger-Python/__init__.py
Fixing default template experience for Python to be in line with published docs: https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-cosmosdb-v2#trigger---python-example.
=> Treat id for cosmos db document as key

FallBackFolderBuild/extensions.json, Functions.Templates/Bindings/bindings.json, Functions.Templates/Templates/DurableFunctionsActivity-CSharp/metadata.json, Functions.Templates/Templates/DurableFunctionsActivity-JavaScript/metadata.json, Functions.Templates/Templates/DurableFunctionsActivity-TypeScript/metadata.json, Functions.Templates/Templates/DurableFunctionsHttpStart-CSharp/metadata.json, Functions.Templates/Templates/DurableFunctionsHttpStart-JavaScript/metadata.json, Functions.Templates/Templates/DurableFunctionsHttpStart-TypeScript/metadata.json, Functions.Templates/Templates/DurableFunctionsOrchestration-CSharp/build.config/template.json, Functions.Templates/Templates/DurableFunctionsOrchestration-CSharp/metadata.json, Functions.Templates/Templates/DurableFunctionsOrchestrator-CSharp/metadata.json, Functions.Templates/Templates/DurableFunctionsOrchestrator-JavaScript/metadata.json, Functions.Templates/Templates/DurableFunctionsOrchestrator-TypeScript/metadata.json
This PR updates the templates to the latest version of the Durable Functions nuget extension:
https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.DurableTask/1.8.3
Release notes:
https://github.com/Azure/azure-functions-durable-extension/releases
=> Updated Durable Functions extension to 1.8.3

Functions.Templates/Templates/DurableFunctionsHttpStart-CSharp-1.x/metadata.json, Functions.Templates/Templates/DurableFunctionsHttpStart-JavaScript/metadata.json, Functions.Templates/Templates/DurableFunctionsHttpStart-TypeScript/metadata.json
Seems like [this change](https://github.com/Azure/azure-functions-templates/pull/900) was recently pushed to the staging templates for v2, but it makes it annoying for our unit tests in VS Code if v2 and v3 templates are different. So I cherry picked the commit over to the v3 branch
=> Enable authLevel prompt for durable http starter functions

Functions.Templates/ProjectTemplate/CSharp/host.json, Functions.Templates/ProjectTemplate/FSharp/host.json
Seems like the `samplingExcludedTypes` is actually under `samplingSettings` and is simply `excludedTypes` itself as seen in [this line](https://github.com/Azure/azure-functions-host/blob/123813c244919360c4fbd54f01ee52986989562b/src/WebJobs.Script/Config/ApplicationInsightsLoggerOptionsSetup.cs#L58).
This was brought up on a [docs issue](https://github.com/MicrosoftDocs/azure-docs/issues/50233) since this file is used for new projects.
=> Fix excludedTypes settings in generated host.json

Build/PackageFiles/ExtensionBundleTemplates-1.x.nuspec, Build/PackageFiles/ExtensionBundleTemplates-2.x.nuspec, Build/PackageFiles/Templates.nuspec, Functions.Templates/Templates/BlobTrigger-Custom/function.json, Functions.Templates/Templates/BlobTrigger-Custom/metadata.json, Functions.Templates/Templates/CosmosDBTrigger-Custom/function.json, Functions.Templates/Templates/CosmosDBTrigger-Custom/metadata.json, Functions.Templates/Templates/EventGridTrigger-Custom/function.json, Functions.Templates/Templates/EventGridTrigger-Custom/metadata.json, Functions.Templates/Templates/EventHubTrigger-Custom/function.json, Functions.Templates/Templates/EventHubTrigger-Custom/metadata.json, Functions.Templates/Templates/HttpTrigger-Custom/function.json, Functions.Templates/Templates/HttpTrigger-Custom/metadata.json, Functions.Templates/Templates/IoTHubTrigger-Custom/function.json, Functions.Templates/Templates/IoTHubTrigger-Custom/metadata.json, Functions.Templates/Templates/QueueTrigger-Custom/function.json, Functions.Templates/Templates/QueueTrigger-Custom/metadata.json, Functions.Templates/Templates/SendGrid-Custom/function.json, Functions.Templates/Templates/SendGrid-Custom/metadata.json, Functions.Templates/Templates/ServiceBusQueueTrigger-Custom/function.json, Functions.Templates/Templates/ServiceBusQueueTrigger-Custom/metadata.json, Functions.Templates/Templates/ServiceBusTopicTrigger-Custom/function.json, Functions.Templates/Templates/ServiceBusTopicTrigger-Custom/metadata.json, Functions.Templates/Templates/SignalRConnectionInfoHttpTrigger-Custom/function.json, Functions.Templates/Templates/SignalRConnectionInfoHttpTrigger-Custom/metadata.json, Functions.Templates/Templates/TimerTrigger-Custom/function.json, Functions.Templates/Templates/TimerTrigger-Custom/metadata.json
Purely because core-tools v3.x has a dependency on 3.x versions
https://github.com/Azure/azure-functions-core-tools/blob/v3.x/build/Settings.cs
=> Port templates for custom handlers (#964)

Functions.Templates/Resources/Resources.resx
Adding `entityTrigger_activity_label` to Resources.resx to make it consistent with bindings.json.
=> Adding entity label to Resources.resx

Functions.Templates/Bindings/bindings.json, Functions.Templates/Templates/DurableFunctionsActivity-CSharp-2.x/metadata.json, Functions.Templates/Templates/DurableFunctionsActivity-PowerShell-2.x/metadata.json, Functions.Templates/Templates/DurableFunctionsActivity-Python-2.x/metadata.json, Functions.Templates/Templates/DurableFunctionsEntity-JavaScript/metadata.json, Functions.Templates/Templates/DurableFunctionsEntity-TypeScript/metadata.json, Functions.Templates/Templates/DurableFunctionsEntityClass-CSharp-2.x/metadata.json, Functions.Templates/Templates/DurableFunctionsEntityFunction-CSharp-2.x/metadata.json, Functions.Templates/Templates/DurableFunctionsEntityHttp-CSharp-2.x/metadata.json, Functions.Templates/Templates/DurableFunctionsEntityHttpStart-CSharp-2.x/metadata.json, Functions.Templates/Templates/DurableFunctionsEntityHttpStart-JavaScript/metadata.json, Functions.Templates/Templates/DurableFunctionsEntityHttpStart-TypeScript/metadata.json, Functions.Templates/Templates/DurableFunctionsHttpStart-CSharp-2.x/metadata.json, Functions.Templates/Templates/DurableFunctionsHttpStart-CSharp/metadata.json, Functions.Templates/Templates/DurableFunctionsHttpStart-PowerShell-2.x/metadata.json, Functions.Templates/Templates/DurableFunctionsHttpStart-Python-2.x/metadata.json, Functions.Templates/Templates/DurableFunctionsOrchestration-CSharp-2.x/metadata.json, Functions.Templates/Templates/DurableFunctionsOrchestrator-CSharp-2.x/metadata.json, Functions.Templates/Templates/DurableFunctionsOrchestrator-CSharp/metadata.json, Functions.Templates/Templates/DurableFunctionsOrchestrator-PowerShell-2.x/metadata.json, Functions.Templates/Templates/DurableFunctionsOrchestrator-Python-2.x/metadata.json
Updated `Microsoft.Azure.WebJobs.Extensions.DurableTask` version from `2.3.0` to `2.3.1`.
=> Updating DurableTask version to 2.3.1

Build/PackageFiles/ExtensionBundleTemplates-2.x.nuspec
Somehow the CI did not catch this while merging my previous PR, but apparently there was a missing `-2.x` suffix in the nuspec file for Durable Functions Python
=> Fixed gulp-build error due to faulty path in nuspec file

Functions.Templates/Templates/EventHubTrigger-Python/function.json
Fix for #971.
The `__init__.py` file has a parameter called `events`, but the `function.json` file named the parameter `event`. This fixes the name in the json.
=> Fixed the parameter name for Python event hubs template

Build/PackageFiles/ExtensionBundleTemplates-1.x.nuspec, Build/PackageFiles/Templates.nuspec, Functions.Templates/Templates/DurableFunctionsActivity-Python-1.x/__init__.py, Functions.Templates/Templates/DurableFunctionsActivity-Python-1.x/function.json, Functions.Templates/Templates/DurableFunctionsActivity-Python-1.x/metadata.json, Functions.Templates/Templates/DurableFunctionsHttpStart-Python-1.x/__init__.py, Functions.Templates/Templates/DurableFunctionsHttpStart-Python-1.x/function.json, Functions.Templates/Templates/DurableFunctionsHttpStart-Python-1.x/metadata.json, Functions.Templates/Templates/DurableFunctionsOrchestrator-Python-1.x/__init__.py, Functions.Templates/Templates/DurableFunctionsOrchestrator-Python-1.x/function.json, Functions.Templates/Templates/DurableFunctionsOrchestrator-Python-1.x/metadata.json
Since the VSCode plugin defaults to bundles V1 at project creation time, removing the Durable Python templates caused users not to be able to scaffold Durable Python projects. This PR adds the templates back.
=> Add Python Durable templates back

Functions.Templates/Templates/DurableFunctionsHttpStart-Python-1.x/function.json, Functions.Templates/Templates/DurableFunctionsOrchestrator-Python-1.x/function.json
This PR removes and fixes incorrect template binding names in V1 for Durable Python.
=> Use safer binding names for Durable Python in V1

Functions.Templates/Bindings/bindings.json, Functions.Templates/Templates/KafkaOutput-CSharp/.template.config/template.json, Functions.Templates/Templates/KafkaOutput-CSharp/KafkaOutputCSharp.cs, Functions.Templates/Templates/KafkaOutput-CSharp/function.json, Functions.Templates/Templates/KafkaOutput-CSharp/metadata.json, Functions.Templates/Templates/KafkaOutput-CSharp/readme.md, Functions.Templates/Templates/KafkaOutput-JavaScript/function.json, Functions.Templates/Templates/KafkaOutput-JavaScript/readme.md, Functions.Templates/Templates/KafkaOutput-PowerShell/function.json, Functions.Templates/Templates/KafkaOutput-PowerShell/readme.md, Functions.Templates/Templates/KafkaOutput-Python/function.json, Functions.Templates/Templates/KafkaOutput-Python/readme.md, Functions.Templates/Templates/KafkaOutput-TypeScript/function.json, Functions.Templates/Templates/KafkaOutput-TypeScript/readme.md, Functions.Templates/Templates/KafkaTrigger-CSharp/.template.config/template.json, Functions.Templates/Templates/KafkaTrigger-CSharp/KafkaTriggerCSharp.cs, Functions.Templates/Templates/KafkaTrigger-CSharp/function.json, Functions.Templates/Templates/KafkaTrigger-CSharp/metadata.json, Functions.Templates/Templates/KafkaTrigger-CSharp/readme.md, Functions.Templates/Templates/KafkaTrigger-Custom/function.json, Functions.Templates/Templates/KafkaTrigger-JavaScript/function.json, Functions.Templates/Templates/KafkaTrigger-JavaScript/readme.md, Functions.Templates/Templates/KafkaTrigger-PowerShell/function.json, Functions.Templates/Templates/KafkaTrigger-PowerShell/readme.md, Functions.Templates/Templates/KafkaTrigger-Python/function.json, Functions.Templates/Templates/KafkaTrigger-Python/readme.md, Functions.Templates/Templates/KafkaTrigger-TypeScript/function.json, Functions.Templates/Templates/KafkaTrigger-TypeScript/readme.md
I create the Kafka extension template, however, the template include an issue. 
We use `%Password%` to set the password, and fetch it from AppSettings, however, it doesn't work on Azure. 
Probably, it is reserved word. 
I switch it into `%EventHubsConnectionString%` since the broker template is written for EventHubs Kafka API. 
I'll Create v3 PR as well. 
CC: @pragnagopa
=> [v2.x] Update Kafka Extension related %Password% AppSettings 

Functions.Templates/ProjectTemplate/CSharp-Isolated/Company.FunctionApp.csproj
Updating worker packages to latest versions in dotnet isolated template.
- [Microsoft.Azure.Functions.Worker](https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker/) : 1.5.2 to 1.6.0
- [Microsoft.Azure.Functions.Worker.Sdk](https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Sdk/) : 1.2.0 to 1.3.0
These versions now match with what is in [v4 branch](https://github.com/Azure/azure-functions-templates/blob/v4.x/Functions.Templates/ProjectTemplate/CSharp-Isolated/Company.FunctionApp.csproj#L9).
=> Updating worker packages to latest versions in dotnet isolated template

Functions.Templates/ProjectTemplate/CSharp/_gitignore, Functions.Templates/ProjectTemplate/FSharp/_gitignore
When using the Azurite Extension in Visual Studio Code (<https://marketplace.visualstudio.com/items?itemName=Azurite.azurite>) several files get created by this extension in the Azure Functions project directory that are only relevant for local development. In analogy to e.g. `local.settings.json` they should be ignored by git by default and therefore be part of the standard `.gitignore` template.
This pull request contains the proposed changes for the C# and F# template (see also merged pull request for VS Code Azure Functions extension <https://github.com/microsoft/vscode-azurefunctions/pull/2972>)
=> Ignore Azurite Files in Function App

Functions.Templates/Templates/TimerTrigger-PowerShell/readme.md
Azure Functions cron expressions don't express year.  The 6th value is for day of the week.  This same change needs to happen in all the other language readme files.
=> Update TimerTrigger Readme

Functions.Templates/ProjectTemplate/CSharp-Isolated/.template.config/GlobalUsings.cs, Functions.Templates/ProjectTemplate/CSharp-Isolated/.template.config/template.json, Functions.Templates/ProjectTemplate/CSharp-Isolated/Company.FunctionApp.csproj, Functions.Templates/ProjectTemplate/CSharp-Isolated/Program.cs
We'd want to move global usings to Azure SDK when possible, but this would get it started. I looked at updating item templates, but that would break existing projects.
Includes fix from PR #1145
@jamesmontemagno
=> Updated for global usings

Functions.Templates/Templates/HttpTriggerWithOpenAPI-CSharp/.template.config/template.json
This PR is to update the OpenAPI extension version from `0.7.2-preview` to `1.0.0` which was GA in November, 2021, for the v4.x runtime.
=> Update version for the OpenAPI extension (v4.x)

Functions.Templates/Templates/HttpTriggerWithOpenAPI-CSharp/.template.config/template.json
This PR is to update the OpenAPI extension version from `0.7.2-preview` to `1.0.0`, which was GA in November, 2021, for the v3.x runtime.
=> Update version for the OpenAPI extension (v3.x)

Functions.Templates/Templates/DurableFunctionsOrchestration-CSharp-2.x/.template.config/template.json
As in title, part of our release process in: https://github.com/Azure/azure-functions-durable-extension/issues/2064
=> Update DurableTask Extension version to 2.6.1 (v4.x)

Functions.Templates/Templates/DurableFunctionsOrchestration-CSharp-2.x/.template.config/template.json
As in title, part of our release process in: https://github.com/Azure/azure-functions-durable-extension/issues/2064
=> Update DurableTask Extension version to 2.6.1 (v3.x)

Functions.Templates/ProjectTemplate/CSharp/Company.FunctionApp.csproj, Functions.Templates/ProjectTemplate/FSharp/Company.FunctionApp.fsproj
Updating in-proc project template to use the [4.1.0 version of Microsoft.NET.Sdk.Functions](https://www.nuget.org/packages/Microsoft.NET.Sdk.Functions/4.1.0). This version inclues the fix for the below issue.
[Binding metrics not emitted for in-proc precompiled applications](https://github.com/Azure/azure-functions-host/issues/8059)
=> Updating In-proc .csproj to use Microsoft.NET.Sdk.Functions 4.1.0

Functions.Templates/Templates/ServiceBusQueueTrigger-CSharp/ServiceBusQueueTriggerCSharp.cs
The class should not be static in order to support dependency injection https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection
=> Removed static modifier from class, fixed #1159

azure-pipelines.yml
Per [this announcement](https://github.com/actions/virtual-environments/issues/4312), `vs2017-win2016` is deprecated. This PR will update the VM Image for `azure-pipelines.yml`
=> Changing to windows-latest

Functions.Templates/ProjectTemplate_v3.x/CSharp/Company.FunctionApp.csproj, Functions.Templates/ProjectTemplate_v3.x/FSharp/Company.FunctionApp.fsproj
Updating `Microsoft.NET.Sdk.Functions` package version to [3.1.0](https://www.nuget.org/packages/Microsoft.NET.Sdk.Functions/3.1.0), which has the below fix.
[V3 backport-Include all bindings when generating function metadata #542](https://github.com/Azure/azure-functions-vs-build-sdk/pull/547)
=> Updating Microsoft.NET.Sdk.Functions to 3.1.0 in dotnet v3 in-proc templates

Build/PackageFiles/Dotnet_precompiled/ProjectTemplates-Isolated_v3.x.nuspec, Build/PackageFiles/Dotnet_precompiled/ProjectTemplates-Isolated_v4.x.nuspec, Build/PackageFiles/Dotnet_precompiled/ProjectTemplates_v3.x.nuspec, Build/PackageFiles/Dotnet_precompiled/ProjectTemplates_v4.x.nuspec, Functions.Templates/ProjectTemplate_v3.x/CSharp-Isolated/Properties/launchSettings.json, Functions.Templates/ProjectTemplate_v3.x/CSharp/Properties/launchSettings.json, Functions.Templates/ProjectTemplate_v4.x/CSharp-Isolated/Properties/launchSettings.json, Functions.Templates/ProjectTemplate_v4.x/CSharp/Properties/launchSettings.json
This is the first pull request to introduce launchSettings.json to Azure Functions projects. The current settings in the launchSettings does not alter any project behavior. There will be more follow-up PRs to enable the following scenarios: 
1. Ability to add a random available port to the launchSettings.json (through the port commandlineargs) so that 2 different Azure Functions projects can run simultaneously without port conflicts. We want to make it similar to how ASP.NET Core projects handle IISExpress and Kestrel ports.  
2. Ability to update the launchBrowser settings to true when a HttpTrigger item template is added. 
/cc @BillHiebert @phenning
=> Adding default launchSetting.json for .NET Templates

Functions.Templates/ProjectTemplate_v3.x/CSharp-Isolated/.template.config/template.json, Functions.Templates/ProjectTemplate_v3.x/CSharp-Isolated/Properties/launchSettings.json, Functions.Templates/ProjectTemplate_v3.x/CSharp/.template.config/template.json, Functions.Templates/ProjectTemplate_v3.x/CSharp/Properties/launchSettings.json, Functions.Templates/ProjectTemplate_v4.x/CSharp-Isolated/.template.config/template.json, Functions.Templates/ProjectTemplate_v4.x/CSharp-Isolated/Properties/launchSettings.json, Functions.Templates/ProjectTemplate_v4.x/CSharp/.template.config/template.json, Functions.Templates/ProjectTemplate_v4.x/CSharp/Properties/launchSettings.json
This change is to ensure that more than one Azure functions project created from VS or the commandline can be run without any other modifications. 
With this change, every new Azure function project that gets created will be assigned an available port between 7000 & 7300. The default value for the port is 7071
=> Automatically generate Http port for Azure Functions project

Functions.Templates/ProjectTemplate_v3.x/CSharp-Isolated/Company.FunctionApp.csproj, Functions.Templates/ProjectTemplate_v4.x/CSharp-Isolated/Company.FunctionApp.csproj, Functions.Templates/ProjectTemplate_v4.x/FSharp-Isolated/Company.FunctionApp.fsproj
Removing `OutputItemType="Analyzer"` from Sdk package reference entry  in project file, as it is not really needed.
=> Removing OutputItemType attribute from Sdk package reference entry in project file

Functions.Templates/ProjectTemplate_v3.x/CSharp/Company.FunctionApp.csproj, Functions.Templates/ProjectTemplate_v3.x/FSharp/Company.FunctionApp.fsproj, Functions.Templates/ProjectTemplate_v4.x/CSharp/Company.FunctionApp.csproj, Functions.Templates/ProjectTemplate_v4.x/FSharp/Company.FunctionApp.fsproj
Update Microsoft.NET.Sdk.Functions package version to [4.11](https://www.nuget.org/packages/Microsoft.NET.Sdk.Functions/4.1.1)(v4) & [3.11](https://www.nuget.org/packages/Microsoft.NET.Sdk.Functions/3.1.1)(v3) in in-proc template
=> Update Microsoft.NET.Sdk.Functions package version to 4.11(v4) & 3.11(v3) in in-proc template

Functions.Templates/Templates/EventHubTrigger-CSharp-5.x/EventHubTriggerCSharp.cs
Fixes #1226 
Fixing the boiler plate code for event hub trigger(inproc) where the incorrect case (camelCase) was used for the `EventBody` property name.
=> Fix incorrect case of EventBody property name in Event hub trigger boiler plate code

Functions.Templates/ProjectTemplate_v4.x/CSharp-Isolated/Company.FunctionApp.csproj, Functions.Templates/ProjectTemplate_v4.x/FSharp-Isolated/Company.FunctionApp.fsproj
Bumping Microsoft.Azure.Functions.Worker to 1.8.0 for dotnet-isolated templates
=> Microsoft.Azure.Functions.Worker version bump to 1.8.0 for dotnet-isolated 

Functions.Templates/Templates/DurableFunctionsEntityHttp-CSharp-2.x/DurableFunctionsEntityHttpCSharp.cs, Functions.Templates/Templates/DurableFunctionsOrchestration-CSharp-1.x/DurableFunctionsOrchestrationCSharp.cs, Functions.Templates/Templates/DurableFunctionsOrchestration-CSharp-2.x/DurableFunctionsOrchestrationCSharp.cs
This uses nameof wherever possible instead of magic strings. This makes navigating to the symbols (F12 in Visual Studio) much easier and more convenient. It also avoids errors when renaming a method.
=> Updated durable functions templates in C# to use nameof 

Functions.Templates/Templates/EventHubTrigger-Python/__init__.py, Functions.Templates/Templates/EventHubTrigger-Python/function.json
The event hub Python trigger was recently updated to have single cardinality, but the `cardinality` field itself was not updated, meaning creating a new event hub python trigger would lead to a functions app that would crash.
This PR reverts the single cardinality back to many, keeping this trigger in-line with the other event hub triggers. Fixes
#1250
=> Reverting Event Hub Python template to use many cardinality

Functions.Templates/Templates/SqlInputBinding-JavaScript/index.js, Functions.Templates/Templates/SqlInputBinding-Typescript/index.ts, Functions.Templates/Templates/SqlOutputBinding-JavaScript/index.js, Functions.Templates/Templates/SqlOutputBinding-Typescript/index.ts
Based off PowerShell Templates PR:
https://github.com/Azure/azure-functions-templates/pull/1262#discussion_r992737774
Updating instructions to instruct users to use 4.x versions instead of 3.x.
Python instructions are already updated, as well as PowerShell.
=> Update SQL Binding JS/TS instructions to change bundle preview to 4.x

Build/PackageFiles/Dotnet_precompiled/ItemTemplates_v3.x.nuspec, Build/PackageFiles/Dotnet_precompiled/ItemTemplates_v4.x.nuspec
We recently learned that none of our Entity templates for C# are showing up in VSCode, in any of the template categories.
I **suspect** this is because those templates were not listed in the `ItemTemplates` files in this repo, which would have been an oversight.
@soninaren: can you please confirm that this theory makes sense?
Additionally, I noticed that these files are under a directory called "Dotnet_precompiled". What does the "precompiled" mean in this context?
=> Add missing C# DF Entity templates to the v3 and v4 ItemTemplate files

Functions.Templates/Templates/QueueTrigger-TypeScript/index.ts
The queue message can be a string but can also be a JSON object. 
@ggailey777
@soninaren
=> fix type for queueMessage

Functions.Templates/Templates/EventHubTrigger-CSharp-5.x/.template.config/template.json, Functions.Templates/Templates/EventHubTrigger-CSharp-Isolated/.template.config/template.json, Functions.Templates/Templates/EventHubTrigger-FSharp-Isolated/.template.config/template.json, Functions.Templates/Templates/EventHubTrigger-FSharp/.template.config/template.json
The focus of these changes is to bump the Event Hubs extension package version for v5-based templates.
=> [Event Hubs Extension] Bump package version

Functions.Templates/Templates/DurableFunctionsOrchestrator-TypeScript/metadata.json
The default name wasn't changed from JS.
=> Fix default function name for DurableFunctionsOrchestrator-TypeScript

Build/PackageFiles/Dotnet_precompiled/ItemTemplates-Isolated_v4.x.nuspec, Build/PackageFiles/ExtensionBundle/ExtensionBundleTemplates-4.x.nuspec, Functions.Templates/Templates/SqlInputBinding-CSharp-Isolated/SqlInputBindingHttpTriggerCSharp.cs, Functions.Templates/Templates/SqlOutputBinding-CSharp-Isolated/SqlOutputBindingHttpTriggerCSharp.cs, Functions.Templates/Templates/SqlTrigger-CSharp-Isolated/.template.config/template.json, Functions.Templates/Templates/SqlTrigger-CSharp-Isolated/SqlTriggerBindingCSharp.cs
While testing the isolated .net 7 issue, I realized we missed adding isolated templates for sql trigger.
-  Fix typo on json
- Add SqlTrigger templates to ExtensionBundle 4.x and to ItemTemplate-Isolated 4.x
=> fix sqltrigger typo and add sqltrigger to extensionbundle templates 4.x

Docs/Actions/ReplaceTokensInText.md, Docs/Actions/ShowMarkdownPreview.md, Docs/Actions/appendToFile.md, Functions.Templates/Templates-v2/TimerTrigger-Python/blueprint_body.py, Functions.Templates/Templates-v2/TimerTrigger-Python/function_app.py, Functions.Templates/Templates-v2/TimerTrigger-Python/function_body.py, Functions.Templates/Templates-v2/TimerTrigger-Python/timer_trigger_template.md
Updated timer trigger functions for python v2.
timer_trigger is the new alias for schedule for v2 timer trigger templates
the runOnStartup property for timer triggers determines whether the function should run immediately when the function app starts, rather than waiting for the scheduled time. By default, this property is set to false. There are several reasons for this default setting:
- Timer functions are typically used for scheduled tasks based on a specific timetable (e.g., every hour, daily, etc.). Setting runOnStartup to false ensures that the function runs according to its defined schedule, maintaining the predictability of executions.
- If runOnStartup were true by default, every time the function app restarts (which can happen for various reasons like deployments, platform …
=> Renamed schedule to timer_trigger for py functions

Functions.Templates/Templates/TimerTrigger-TypeScript/index.ts
This PR addresses this issue: https://github.com/Azure/azure-functions-nodejs-library/issues/63.
A customer asked us to update the function signature for Timer triggers to use a `Timer` type instead of `any`.
Duplicate of #1488.
=> Switch any to Timer type

Functions.Templates/ProjectTemplate_v4.x/CSharp-Isolated/Company.FunctionApp.csproj, Functions.Templates/ProjectTemplate_v4.x/FSharp-Isolated/Company.FunctionApp.fsproj, Functions.Templates/Templates/BlobTrigger-CSharp-Isolated/.template.config/template.json, Functions.Templates/Templates/BlobTrigger-FSharp-Isolated/.template.config/template.json, Functions.Templates/Templates/CosmosDBTrigger-CSharp-Isolated/.template.config/template.json, Functions.Templates/Templates/CosmosDBTrigger-FSharp-Isolated/.template.config/template.json, Functions.Templates/Templates/EventHubTrigger-CSharp-Isolated/.template.config/template.json, Functions.Templates/Templates/EventHubTrigger-FSharp-Isolated/.template.config/template.json, Functions.Templates/Templates/HttpTrigger-CSharp-Isolated-NetCore/.template.config/template.json, Functions.Templates/Templates/HttpTrigger-CSharp-Isolated/.template.config/template.json, Functions.Templates/Templates/QueueTrigger-CSharp-Isolated/.template.config/template.json, Functions.Templates/Templates/QueueTrigger-FSharp-Isolated/.template.config/template.json, Functions.Templates/Templates/ServiceBusQueueTrigger-CSharp-Isolated/.template.config/template.json, Functions.Templates/Templates/ServiceBusTopicTrigger-CSharp-Isolated/.template.config/template.json, Functions.Templates/Templates/SignalRConnectionInfoHttpTrigger-CSharp-Isolated/.template.config/template.json
Moving package references to latest versions.
Extension packages referenced:
=> Updating dependency versions for .NET Isolated projects 

Functions.Templates/ProjectTemplate_v4.x/CSharp-Isolated/Company.FunctionApp.csproj, Functions.Templates/ProjectTemplate_v4.x/FSharp-Isolated/Company.FunctionApp.fsproj
Updating Microsoft.Azure.Functions.Worker.Sdk to 1.17.0 in dotnet isolated templates.
https://github.com/Azure/azure-functions-dotnet-worker/releases/tag/sdk-1.17.0
=> Updating Microsoft.Azure.Functions.Worker.Sdk to 1.17.0 in dni templates

Functions.Templates/Templates/DurableFunctionsOrchestration-CSharp-Isolated/.template.config/template.json
In the future, we need to make sure this is in lockstep with the HTTP extension changes.
=> Update Durable reference to HTTP extension

Functions.Templates/Templates/DurableFunctionsOrchestration-CSharp-Isolated/.template.config/template.json, Functions.Templates/Templates/DurableFunctionsOrchestration-CSharp-Isolated/DurableFunctionsOrchestrationCSharp.cs
We've received recent reports that the DF templates for .NET isolated have stopped working out of the box. This PR makes 3 fixes to address the feedback:
1. Updates the DF isolated extension to version 1.1.1 (can I use a `*` pattern to have it always download the latest?)
2. Updates the Http extension to version 3.1.0 (was getting the following warning otherwise)
"""
Warning As Error: Detected package downgrade: Microsoft.Azure.Functions.Worker.Extensions.Http from 3.1.0 to 3.0.13. Reference the package directly from the project to select a different version.
FunctionApp2 -> Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore 1.2.0 -> Microsoft.Azure.Functions.Worker.Extensions.Http (>= 3.1.0)
FunctionApp2 -> Microsoft.Azure.Functions.Worker.Extensions.Http (>= 3.0.13)
"""
3. …
=> Patch .NET isolated DF templates

azure-pipelines.yml
Skipping One loc build step for PRs sent from forks
=> Skipping oneLoc build for PRs from forks

Functions.Templates/Templates/HttpTrigger-CSharp-Isolated/.template.config/template.json
This PR adds .NET 9 as a target framework when creating a new HttpTrigger via core tools
Resolves: https://github.com/Azure/azure-functions-dotnet-worker/issues/2560
=> .NET 9 template change for HttpTrigger
