- Bindings/bindings.json
Changes:
- changed version to use date based format
- added <TBD> to schema version
- applied consistent formatting to JSON
- Added "defaultParameterName" for the default value for a new input
- Added "isTrigger" to signal if the binding type is a trigger
- Added "defaultValue" for various settings
- Corrected "direction" 
- For triggers, in
- input -> in, output -> out
> bindings.json changes to keep up with scripts changes

- Templates/TimerTrigger-CSharp/function.json
- add name for timer binding to match the code
- change schedule to once a minute
> Fix timer trigger csharp template

- Templates/BlobTrigger/index.js
- Templates/EventHubTrigger/function.json
- Templates/EventHubTrigger/index.js
- Templates/EventHubTrigger/metadata.json
- Templates/HttpTrigger/function.json
- Templates/HttpTrigger/index.js
- Templates/ManualTrigger/function.json
- Templates/ManualTrigger/index.js
- Templates/ManualTrigger/metadata.json
- Templates/QueueTrigger/index.js
- Templates/QueueTrigger/metadata.json
- Templates/TimerTrigger/function.json
- Templates/TimerTrigger/index.js
- Templates/WebHook-Generic/function.json
- Templates/WebHook-Generic/index.js
- Templates/WebHook-Generic/metadata.json
- Templates/WebHook-GitHub/function.json
- Templates/WebHook-GitHub/index.js
- Templates/WebHook-GitHub/metadata.json
Updates:
- Changed the format to use new "context first" format (https://github.com/Azure/azure-webjobs-sdk-script/pull/70)
- Removed output bindings and cleaned up function.json
- Modified metadata.json to use current format
> Update JavaScript Samples to use new format & their template metadata

- Templates/WebHook-Generic/index.js
- Templates/WebHook-GitHub/index.js
Found some glitches in the gh wh template which didn't get caught. Can't wait for e2e testing. :)
> Fix bugs in GH WebHook Example

- Templates/WebHook-Generic-CSharp/function.json
- Templates/WebHook-Generic-CSharp/metadata.json
- Templates/WebHook-Generic-CSharp/run.csx
- Templates/WebHook-Generic-CSharp/sample.dat
That's the cleanest I could do with current runtime. Later, I'd like to find a way to directly receive the dynamic `data` as a function param instead of having to manually use json.net.
> Add C# WebHook template

- Bindings/bindings.json
adding NotificationHub out binding
> adding NotificationHub binding

- Templates/BlobTrigger-CSharp/metadata.json
- Templates/BlobTrigger-NodeJS/metadata.json
- Templates/Empty-CSharp/metadata.json
- Templates/Empty-NodeJS/metadata.json
- Templates/EventHubTrigger-NodeJS/metadata.json
- Templates/GenericWebHook-CSharp/metadata.json
- Templates/GenericWebHook-NodeJS/metadata.json
- Templates/GitHubWebHook-NodeJS/metadata.json
- Templates/HttpTrigger-Batch/metadata.json
- Templates/HttpTrigger-CSharp/metadata.json
- Templates/HttpTrigger-NodeJS/metadata.json
- Templates/ManualTrigger-NodeJS/metadata.json
- Templates/QueueTrigger-Bash/metadata.json
- Templates/QueueTrigger-Batch/metadata.json
- Templates/QueueTrigger-CSharp/metadata.json
- Templates/QueueTrigger-FSharp/metadata.json
- Templates/QueueTrigger-NodeJS/metadata.json
- Templates/QueueTrigger-Php/metadata.json
- Templates/QueueTrigger-Powershell/metadata.json
- Templates/QueueTrigger-Python/metadata.json
- Templates/ServiceBusQueueTrigger-NodeJS/metadata.json
- Templates/TimerTrigger-CSharp/metadata.json
- Templates/TimerTrigger-NodeJS/metadata.json
Adding template descriptions that can be surfaced in the UX.
> adding template descriptions

- Templates/QueueTrigger-NodeJS/metadata.json
This should be in Core + Data Processing. I just tested it in PROD - it works great!
> Promoting Node.js QueueTrigger template

- Templates.sln
- Templates/BlobTrigger-Batch/function.json
- Templates/BlobTrigger-Batch/metadata.json
- Templates/BlobTrigger-Batch/run.bat
> Adding BlobTrigger Batch sample

- Templates/ManualTrigger-NodeJS/metadata.json
> Moving Node JS  manual trigger out of Core category

- Templates/HttpTrigger-CSharp/run.csx
> Simplifying C# HTTP trigger template

- Templates/EventHubTrigger-CSharp/function.json
- Templates/EventHubTrigger-CSharp/metadata.json
- Templates/EventHubTrigger-CSharp/run.csx
> Adding Event Hub C# template

- Templates.sln
- Templates/QueueTrigger-FSharp/function.json
- Templates/QueueTrigger-FSharp/metadata.json
- Templates/QueueTrigger-FSharp/run.fsx
This reverts commit 3f3a3860fbf60c0d418b2732ab106514a35d437a.
> Revert "Removing Queue trigger F# template"

- Bindings/bindings.json
- Templates.sln
- Templates/ServiceBusQueueTrigger-NodeJS/function.json
- Templates/ServiceBusQueueTrigger-NodeJS/index.js
- Templates/ServiceBusQueueTrigger-NodeJS/metadata.json
Taking service bus and NH template updates to master
> Merge dev to master

- Bindings/bindings.json
> Adding row key setting for table storage input binding. Updating table and blob bindings.

- Bindings/bindings.json
- Templates/ServiceBusQueueTrigger-CSharp/function.json
- Templates/ServiceBusQueueTrigger-CSharp/metadata.json
- Templates/ServiceBusQueueTrigger-CSharp/run.csx
> Adding Service Bus C# template & fixing bindings.json to open service bus connections string blade

- Bindings/bindings.json
I'm just sending this out for a code review but I don't want to merge this until Ibiza is finished deploying.
> Added API Hub File Bindings (don't merge)

- Templates.sln
- Templates/BlobTrigger-CSharp/run.csx
- Templates/EventHubTrigger-CSharp/run.csx
- Templates/GenericWebHook-CSharp/run.csx
- Templates/GitHubWebHook-CSharp/run.csx
- Templates/HttpTrigger-CSharp/run.csx
- Templates/ManualTrigger-CSharp/run.csx
- Templates/QueueTrigger-CSharp/run.csx
- Templates/ServiceBusQueueTrigger-CSharp/run.csx
- Templates/TimerTrigger-CSharp/run.csx
See related runtime PR: https://github.com/Azure/azure-webjobs-sdk-script/pull/303
Also fixing up the VS solution to include all the templates.
> Changing C# function TraceWriter calls to log.Info

- Bindings/bindings.json
Replaces https://github.com/Azure/azure-webjobs-sdk-templates/pull/158
> Updating error copy

- Templates/QueueTrigger-Bash/run.sh
I've verified that this fixes the template in prod.
> Fixing Bash template casing issue

- Templates/SasToken-Node/function.json
- Templates/SasToken-Node/index.js
- Templates/SasToken-Node/metadata.json
- Templates/SasToken-Node/package.json
- Templates/SasToken-Node/readme.md
- Templates/SasToken-Node/sample.dat
Code has been reviewed by Dale.
> New Node template for generating an Azure Storage SAS token

- Templates.sln
- Templates/EventHubTrigger-Python/function.json
- Templates/EventHubTrigger-Python/metadata.json
- Templates/EventHubTrigger-Python/run.py
Add a Python template for working with EventHub trigger
> Initial add of EventHubTrigger-Python template

- Bindings/bindings.json
- Templates.sln
- Templates/SendGrid-CSharp/function.json
- Templates/SendGrid-CSharp/metadata.json
- Templates/SendGrid-CSharp/run.csx
- Templates/SendGrid-CSharp/sample.dat
- Templates/SendGrid-NodeJS/function.json
- Templates/SendGrid-NodeJS/index.js
- Templates/SendGrid-NodeJS/metadata.json
- Templates/SendGrid-NodeJS/sample.dat
> adding send grid binding & template, fixing documentDB case, added consumer group regex

- Resources/Resources.resx
- Resources/cs-CZ/Resources.resx
- Resources/de-DE/Resources.resx
- Resources/es-ES/Resources.resx
- Resources/fr-FR/Resources.resx
- Resources/hu-HU/Resources.resx
- Resources/it-IT/Resources.resx
- Resources/ja-JP/Resources.resx
- Resources/ko-KR/Resources.resx
- Resources/nl-NL/Resources.resx
- Resources/pl-PL/Resources.resx
- Resources/pt-BR/Resources.resx
- Resources/pt-PT/Resources.resx
- Resources/ru-RU/Resources.resx
- Resources/sv-SE/Resources.resx
- Resources/tr-TR/Resources.resx
- Resources/zh-CN/Resources.resx
- Resources/zh-TW/Resources.resx
- Templates/HttpGET(CRUD)-PHP/function.json
- Templates/HttpGET(CRUD)-PHP/metadata.json
- Templates/HttpGET(CRUD)-PHP/run.php
However I don't know howto create the translation for `Resources/qps-ploc`
> Template for HTTPGet(CRUD)-PHP

- Documentation/blobTrigger.md
- Documentation/documentDBOut.md
- Documentation/httpTrigger.md
- Documentation/mobileTableIn.md
- Documentation/mobileTableOut.md
- Documentation/notificationHubOut.md
- Documentation/queueOut.md
- Documentation/queueTrigger.md
- Documentation/timerTrigger.md
Needed to make links work in documentation
> Modify links to use md style links

- Bindings/bindings.json
- Documentation/botIn.md
- Documentation/botOut.md
- Resources/Resources.resx
This changeset introduces changes necessary to add surface the bindings for Bot Framework. This includes:
- String changes in Resources.resx
- Configuration settings for in and out bindings for bot
> Adding Bot bindings

- Templates/ExternalFileTrigger-FSharp/metadata.json
- Templates/ExternalTable-FSharp/metadata.json
- Templates/GitHubCommenter-FSharp/project.json
- Templates/GitHubCommenter-FSharp/run.fsx
- Templates/GitHubWebHook-FSharp/project.json
- Templates/GitHubWebHook-FSharp/run.fsx
- Templates/HttpGET(CRUD)-FSharp/run.fsx
- Templates/HttpPOST(CRUD)-FSharp/project.json
- Templates/HttpPOST(CRUD)-FSharp/run.fsx
- Templates/HttpPUT(CRUD)-FSharp/function.json
- Templates/HttpPUT(CRUD)-FSharp/run.fsx
- Templates/HttpTrigger-FSharp/run.fsx
- Templates/ImageResizer-FSharp/run.fsx
- Templates/SasToken-FSharp/project.json
- Templates/SasToken-FSharp/run.fsx
F# template updates for @soninaren
> fsharp template updates

- Documentation/queueOut.md
Sorry for the flyby PR, but I needed to work with queue bindings for batch files and couldn't find any documentation. After some experimentation I was able to figure out how they worked and thought this might be an okay place to share. 
Cheers!
> Proposed: Information for batch files

- Templates/HttpTrigger-JavaScript/function.json
- Templates/HttpTrigger-JavaScript/index.js
resolves https://github.com/Azure/azure-webjobs-sdk-script/issues/1182
> Remove node http binding return default

- Resources/Resources.resx
Closes https://github.com/Azure/azure-webjobs-sdk-templates/issues/408
> Remove preview label from SendGrid & Twilio, and add to Bot bindings

- Resources/Resources.resx
Closes https://github.com/Azure/azure-webjobs-sdk-templates/issues/387
> Improve tooltip help text across the board

- Templates/ExternalFileTrigger-JavaScript/index.js
Changed JS return variable in index.json to match return configured in function.json
> Updated ExternalFileTrigger-JS

- Templates/HttpTrigger-Powershell/run.ps1
I'm submitting this PR because it would have helped me when getting started. As I created my function I went with POST and everything worked fine. I later wanted to use GET but had already deleted the relevant lines because they hadn't previously been useful to me when using POST.
When I created another instance of the sample I had been using a different parameter name than "name" so never mentally made the connection. 👍
> Clarify how to retrieve data between POST and GET

- Resources/Resources.resx
- Typo in Service Bus
- Bot Direct Line Key
> Improve resource strings:

- Functions.Templates/Resources/Resources.resx
- DocumentDb -> Cosmos DB
- Event Hub -> Event Hubs
- Misc label cleanup
> Update binding labels

- Functions.Templates/Bindings/bindings.json
- Functions.Templates/Resources/Resources.resx
> [DocDB] adding partition keys bindings.json

- Functions.Templates/Documentation/ExcelIn.md
- Functions.Templates/Documentation/ExcelOut.md
- Functions.Templates/Documentation/GraphWebhookCreator.md
- Functions.Templates/Documentation/OneDriveIn.md
- Functions.Templates/Documentation/OneDriveOut.md
- Functions.Templates/Documentation/Outlook.md
- Functions.Templates/Documentation/Token.md
Update to documentation/*.md files for O365 bindings
> Update O365 docs

- Functions.Templates/Documentation/cosmosDBTrigger.md
- Functions.Templates/Functions.Templates.csproj
This change adds more detailed documentation to the trigger and explains the properties.
> Adding documentation for the Cosmos DB Trigger

- Functions.Templates/Templates/CosmosDBTrigger-JavaScript/index.js
This change addresses the correct property
> Fixing Cosmos DB Javascript template code

- Functions.Templates/Resources/Resources.resx
- Functions.Templates/Templates/OutlookMessageWebhookCreator-CSharp/function.json
- Functions.Templates/Templates/OutlookMessageWebhookCreator-CSharp/metadata.json
- Functions.Templates/Templates/OutlookMessageWebhookCreator-CSharp/run.csx
- Functions.Templates/Templates/OutlookMessageWebhookDeleter-CSharp/function.json
- Functions.Templates/Templates/OutlookMessageWebhookDeleter-CSharp/metadata.json
- Functions.Templates/Templates/OutlookMessageWebhookDeleter-CSharp/run.csx
- Functions.Templates/Templates/OutlookMessageWebhookHandler-CSharp/function.json
- Functions.Templates/Templates/OutlookMessageWebhookHandler-CSharp/metadata.json
- Functions.Templates/Templates/OutlookMessageWebhookHandler-CSharp/run.csx
- Functions.Templates/Templates/OutlookMessageWebhookRefresher-CSharp/function.json
- Functions.Templates/Templates/OutlookMessageWebhookRefresher-CSharp/metadata.json
- Functions.Templates/Templates/OutlookMessageWebhookRefresher-CSharp/run.csx
- Functions.Templates/Templates/ProfilePhotoAPI-CSharp/run.csx
Targeting dev as this can't go directly onto 2.x. Let me know if/how we want to rebase onto 2.x instead.
> adding webhook templates

- Functions.Templates/Templates/ServiceBusQueueTrigger-FSharp/metadata.json
Fixes https://github.com/Azure/azure-functions-ux/issues/2037
> f# service bus queue trigger fix

- Functions.Templates/Resources/Resources.resx
- Functions.Templates/Templates/AppInsightsHttpAvailability-CSharp/metadata.json
> remove see documentation and change app to application

- Functions.Templates/Templates/HttpGET(CRUD)-PHP/metadata.json
- Functions.Templates/Templates/IoTHubServiceBusQueueTrigger-TypeScript/metadata.json
- Functions.Templates/Templates/IoTHubServiceBusTopicTrigger-TypeScript/metadata.json
- Functions.Templates/Templates/IoTHubTrigger-TypeScript/metadata.json
Fix #619: mark PHP and TypeScript templates as experimental
> Mark PHP and TypeScript templates as experimental

- Functions.Templates/Templates/EventGridTrigger-CSharp/EventGridTriggerCSharp.cs
> use JObject for EventGrid template

- Functions.Templates/Templates/EventGridTrigger-CSharp/sample.dat
- Functions.Templates/Templates/EventGridTrigger-JavaScript/sample.dat
Updated sample.dat files for Event Grid templates to contain an Event Grid message with a valid JSON format
> Updated sample messages for Event Grid templates

- Functions.Templates/Templates/EventGridTrigger-CSharp/build.config/template.json
not sure how to test this or how to enable this template for v1
> update EventGrid nuget version

- Functions.Templates/Bindings/bindings.json
I'm not sure if the versions are correct. The previous ones were 1.0.0-beta1-10005, and I don't see where the "10005" came from.
> Restore graph templates

- Functions.Templates/Templates/HttpTrigger-JavaScript/function.json
- Functions.Templates/Templates/HttpTrigger-Python/function.json
> Set 'methods' on JavaScript and Python httpTrigger

- Functions.Templates/Templates/BlobTrigger-Java/BlobTriggerJava.java
- Functions.Templates/Templates/HttpTrigger-Java/HttpTriggerJava.java
- Functions.Templates/Templates/QueueTrigger-Java/QueueTriggerJava.java
- Functions.Templates/Templates/TimerTrigger-Java/TimerTriggerJava.java
> change package name according to the newest java function dependency

- Functions.Templates/Documentation/eventHubTrigger.md
- Functions.Templates/Documentation/ioTHubTrigger.md
- Functions.Templates/Templates/EventHubTrigger-JavaScript/index.js
Resolves https://github.com/Azure/azure-functions-host/issues/2846
Template works for v1 and v2
> Add examples of looking at EventHub metadata in out of proc languages

- Functions.Templates/Functions.Templates.csproj
- Functions.Templates/PortalTemplates.nuspec
- Functions.Templates/Templates/ServiceBusQueueTrigger-Python/__init__.py
- Functions.Templates/Templates/ServiceBusQueueTrigger-Python/function.json
- Functions.Templates/Templates/ServiceBusQueueTrigger-Python/metadata.json
- Functions.Templates/Templates/ServiceBusQueueTrigger-Python/sample.dat
- Functions.Templates/Templates/ServiceBusTopicTrigger-Python/__init__.py
- Functions.Templates/Templates/ServiceBusTopicTrigger-Python/function.json
- Functions.Templates/Templates/ServiceBusTopicTrigger-Python/metadata.json
- Functions.Templates/Templates/ServiceBusTopicTrigger-Python/sample.dat
Closes: https://github.com/Azure/azure-functions-python-worker/issues/178
> Add ServiceBus templates

- Functions.Templates/Templates/HttpTrigger-Python/function.json
This is required for the quick-start doc.
> Updating auth level for Python Http Trigger

- Functions.Templates/ProjectTemplate/CSharp/local.settings.json
- Functions.Templates/ProjectTemplate/FSharp/local.settings.json
- Functions.Templates/Templates/HttpTrigger-CSharp/HttpTriggerCSharp.cs
> making v2 changes

- Functions.Templates/Templates/EventGridTrigger-CSharp/metadata.json
- Functions.Templates/Templates/EventGridTrigger-JavaScript/metadata.json
- Functions.Templates/Templates/EventGridTrigger-Python/metadata.json
> Update Event Grid Categories

- Functions.Templates/Bindings/bindings.json
- Functions.Templates/Documentation/tableIn.md
- Functions.Templates/Resources/ResourceBinding.Designer.cs
- Functions.Templates/Resources/Resources.resx
Adding table binding support for Portal. Also added documentation and an example for doing multi-row filtering using JArray binding since we are not longer support IQueryable.
> Table binding via Portal + docs for multi-row filtering

- Functions.Templates/PortalTemplates.nuspec
- Functions.Templates/Templates/IoTHubTrigger-CSharp/function.json
- Functions.Templates/Templates/IoTHubTrigger-CSharp/metadata.json
- Functions.Templates/Templates/IoTHubTrigger-CSharp/run.csx
- Functions.Templates/Templates/IoTHubTrigger-CSharp/sample.dat
- Functions.Templates/Templates/IoTHubTrigger-JavaScript/function.json
- Functions.Templates/Templates/IoTHubTrigger-JavaScript/index.js
- Functions.Templates/Templates/IoTHubTrigger-JavaScript/metadata.json
- Functions.Templates/Templates/IoTHubTrigger-JavaScript/sample.dat
* Adding iot hub templates for JS and C#
* Resolving CR comments
* remove references to service bus
> Merging dev to master 

- Functions.Templates/Templates/EventHubTrigger-CSharp/EventHubTriggerCSharp.cs
- Functions.Templates/Templates/EventHubTrigger-CSharp/function.json
> Updating EventHubTrigger template

- Functions.Templates/Templates/BlobTrigger-CSharp/BlobTriggerCSharp.cs
- Functions.Templates/Templates/CosmosDBTrigger-CSharp/CosmosDBTriggerCSharp.cs
- Functions.Templates/Templates/EventGridTrigger-CSharp/EventGridTriggerCSharp.cs
- Functions.Templates/Templates/SendGrid-CSharp/SendGridCSharp.cs
- Functions.Templates/Templates/ServiceBusQueueTrigger-CSharp/ServiceBusQueueTriggerCSharp.cs
- Functions.Templates/Templates/ServiceBusTopicTrigger-CSharp/ServiceBusTopicTriggerCSharp.cs
> Added "using System;" to VS item templates

- Functions.Templates/Templates/HttpTrigger-CSharp/build.config/vs-2017.3.host.json
- Functions.Templates/Templates/HttpTrigger-FSharp/build.config/vs-2017.3.host.json
> Updating text in httpTrigger in VS from "Access rights" to "Authorization level"

- .gitignore
- Functions.Templates/Templates/ServiceBusTopicTrigger-Python/README.md
- Functions.Templates/Templates/ServiceBusTopicTrigger-Python/__init__.py
- Functions.Templates/Templates/ServiceBusTopicTrigger-Python/function.json
This PR addresses Issue #877.
- Uses Black formatting
- Logging content type and body
- Added README file, but no docs yet. 
More work will need to be done, but I wanted to start getting feedback so I go in the right direction.
> #877 python service bus template

- Functions.Templates/ProjectTemplate/CSharp/build.config/template.json
- Functions.Templates/ProjectTemplate/FSharp/build.config/template.json
Makes the template easier to use with `dotnet new`
> Provide default placeholder values for use with dotnet new

- Functions.Templates/Bindings/bindings.json
- Functions.Templates/Resources/Resources.resx
- Functions.Templates/Templates/EventHubTrigger-JavaScript/function.json
- Functions.Templates/Templates/EventHubTrigger-TypeScript/function.json
- Functions.Templates/Templates/IoTHubTrigger-JavaScript/function.json
- Functions.Templates/Templates/IoTHubTrigger-TypeScript/function.json
- Functions.Templates/Templates/TimerTrigger-JavaScript/index.js
- Functions.Templates/Templates/TimerTrigger-TypeScript/index.ts
Resolves https://github.com/Azure/azure-functions-templates/issues/909
> Update timer trigger templates for Node.js

- Functions.Templates/Templates/DurableFunctionsHttpStart-CSharp-1.x/metadata.json
- Functions.Templates/Templates/DurableFunctionsHttpStart-JavaScript/metadata.json
- Functions.Templates/Templates/DurableFunctionsHttpStart-TypeScript/metadata.json
resolves MicrosoftDocs/azure-docs#36896
> (AzureCXP) Enable authLevel prompt for durable http starter functions

- Functions.Templates/ProjectTemplate/CSharp/host.json
> Exclude sampling of requests by default in host.json templates

- Functions.Templates/Templates/HttpTrigger-CSharp/HttpTriggerCSharp.cs
- Functions.Templates/Templates/HttpTrigger-FSharp/HttpTriggerFSharp.fs
- Functions.Templates/Templates/HttpTrigger-JavaScript/index.js
- Functions.Templates/Templates/HttpTrigger-PowerShell/run.ps1
- Functions.Templates/Templates/HttpTrigger-Python/__init__.py
- Functions.Templates/Templates/HttpTrigger-TypeScript/index.ts
> Updating httpTrigger templates to provide a friendly message

- Build/PackageFiles/ExtensionBundleTemplates-1.x.nuspec
- Build/PackageFiles/ExtensionBundleTemplates-2.x.nuspec
- Build/PackageFiles/Templates.nuspec
- Functions.Templates/Templates/DurableFunctionsActivity-PowerShell-1.x/function.json
- Functions.Templates/Templates/DurableFunctionsActivity-PowerShell-1.x/metadata.json
- Functions.Templates/Templates/DurableFunctionsActivity-PowerShell-1.x/run.ps1
- Functions.Templates/Templates/DurableFunctionsActivity-PowerShell-2.x/function.json
- Functions.Templates/Templates/DurableFunctionsActivity-PowerShell-2.x/metadata.json
- Functions.Templates/Templates/DurableFunctionsActivity-PowerShell-2.x/run.ps1
- Functions.Templates/Templates/DurableFunctionsActivity-Python-1.x/metadata.json
- Functions.Templates/Templates/DurableFunctionsActivity-Python-2.x/metadata.json
- Functions.Templates/Templates/DurableFunctionsHttpStart-PowerShell-1.x/function.json
- Functions.Templates/Templates/DurableFunctionsHttpStart-PowerShell-1.x/metadata.json
- Functions.Templates/Templates/DurableFunctionsHttpStart-PowerShell-1.x/run.ps1
- Functions.Templates/Templates/DurableFunctionsHttpStart-PowerShell-2.x/function.json
- Functions.Templates/Templates/DurableFunctionsHttpStart-PowerShell-2.x/metadata.json
- Functions.Templates/Templates/DurableFunctionsHttpStart-PowerShell-2.x/run.ps1
- Functions.Templates/Templates/DurableFunctionsHttpStart-Python-1.x/metadata.json
- Functions.Templates/Templates/DurableFunctionsHttpStart-Python-2.x/metadata.json
- Functions.Templates/Templates/DurableFunctionsOrchestrator-PowerShell-1.x/function.json
- Functions.Templates/Templates/DurableFunctionsOrchestrator-PowerShell-1.x/metadata.json
- Functions.Templates/Templates/DurableFunctionsOrchestrator-PowerShell-1.x/run.ps1
- Functions.Templates/Templates/DurableFunctionsOrchestrator-PowerShell-2.x/function.json
- Functions.Templates/Templates/DurableFunctionsOrchestrator-PowerShell-2.x/metadata.json
- Functions.Templates/Templates/DurableFunctionsOrchestrator-PowerShell-2.x/run.ps1
- Functions.Templates/Templates/DurableFunctionsOrchestrator-Python-1.x/metadata.json
- Functions.Templates/Templates/DurableFunctionsOrchestrator-Python-2.x/metadata.json
* Add PowerShell Durable templates
* Include PowerShell Durable in default templates, bundles v1, v2
* Include Python Durable to default templates
* Add `(preview)` to PowerShell and Python Durable template names
Tested default templates for both, and bundles v1 for PowerShell.
/cc @AnatoliB
> Add PowerShell Durable templates

- Functions.Templates/Templates/TimerTrigger-PowerShell/run.ps1
Fixing typo and formatting in TimerTrigger-PowerShell
> Fixing typo and formatting in TimerTrigger-PowerShell

- Functions.Templates/ProjectTemplate/CSharp/Company.FunctionApp.csproj
- Functions.Templates/ProjectTemplate/FSharp/Company.FunctionApp.fsproj
- Functions.Templates/Resources/Resources.resx
- Functions.Templates/Templates/TimerTrigger-PowerShell/run.ps1
In preparation for releasing Bundle 3.1.1
> Merging dev to master

- Functions.Templates/Bindings/bindings.json
- Functions.Templates/Templates/DurableFunctionsActivity-CSharp-2.x/metadata.json
- Functions.Templates/Templates/DurableFunctionsActivity-PowerShell-2.x/metadata.json
- Functions.Templates/Templates/DurableFunctionsActivity-Python-2.x/metadata.json
- Functions.Templates/Templates/DurableFunctionsHttpStart-CSharp-2.x/metadata.json
- Functions.Templates/Templates/DurableFunctionsHttpStart-CSharp/metadata.json
- Functions.Templates/Templates/DurableFunctionsHttpStart-PowerShell-2.x/metadata.json
- Functions.Templates/Templates/DurableFunctionsHttpStart-Python-2.x/metadata.json
- Functions.Templates/Templates/DurableFunctionsOrchestration-CSharp-2.x/metadata.json
- Functions.Templates/Templates/DurableFunctionsOrchestrator-CSharp-2.x/metadata.json
- Functions.Templates/Templates/DurableFunctionsOrchestrator-CSharp/metadata.json
- Functions.Templates/Templates/DurableFunctionsOrchestrator-PowerShell-2.x/metadata.json
- Functions.Templates/Templates/DurableFunctionsOrchestrator-Python-2.x/metadata.json
Performed a global search-and-replace to properly support the upcoming DurableTask 2.3.0 release
> Updating for DurableTask release 2.3.0

- Functions.Templates/Bindings/bindings.json
- Functions.Templates/Resources/Resources.resx
temporary workaround for https://github.com/microsoft/vscode-azurefunctions/issues/2559
> [RabbitMQ] Update settings.json with additional values

- Functions.Templates/Bindings/bindings.json
- Functions.Templates/Resources/Resources.resx
Port of https://github.com/Azure/azure-functions-templates/commit/0b0cdcadeed8860adf14aafe3e81b7d60992547b
> [Port] Update settings.json with additional values (#997)

- Functions.Templates/ProjectTemplate/CSharp/host.json
- Functions.Templates/ProjectTemplate/FSharp/host.json
Resolves #1001.
Related PR to update schema: https://github.com/SchemaStore/schemastore/pull/1437
> Fixed excludedTypes settings in generated host.json

- Functions.Templates/Templates/DurableFunctionsHttpStart-Python-1.x/function.json
- Functions.Templates/Templates/DurableFunctionsOrchestrator-Python-1.x/function.json
> Promote dev to master for release

- Functions.Templates/Resources/Resources.resx
- Functions.Templates/Resources/ja-JP/Resources/Resources.resx
I found two missing resource on Kafka when I test it.
> Missing resources for kafka

- Functions.Templates/Resources/Resources.resx
- Functions.Templates/Resources/ja-JP/Resources/Resources.resx
I found the resource file missing the Kafka related resource on v3 branch.
> [v3] Missing Resource for Kafka

- Functions.Templates/Bindings/bindings.json
- Functions.Templates/Templates/RabbitMQTrigger-CSharp/.template.config/template.json
- Functions.Templates/Templates/RabbitMQTrigger-CSharp/metadata.json
- Functions.Templates/Templates/RabbitMQTrigger-Custom/metadata.json
- Functions.Templates/Templates/RabbitMQTrigger-JavaScript/metadata.json
- Functions.Templates/Templates/RabbitMQTrigger-PowerShell/metadata.json
- Functions.Templates/Templates/RabbitMQTrigger-Python/metadata.json
- Functions.Templates/Templates/RabbitMQTrigger-TypeScript/metadata.json
Updated versions based on the commit (https://github.com/Azure/azure-functions-templates/commit/ccb1cfbf804c1f1c5551d60bbbb2390c8ba09011)
> Updated version of RabbitMQ from 1.0.0-beta to 1.0.0

- Functions.Templates/Bindings/bindings.json
@TsuyoshiUshio - I can also update the values in the documentation files if desired.
> [v2.x] Added display values to Kafka binding enums.

- Functions.Templates/Bindings/bindings.json
@TsuyoshiUshio - I can also update the enum values in the Kafka documentation files to their display names if desired.
> [v3.x] Added display values to Kafka binding enums.

- Build/PackageFiles/ExtensionBundleTemplates-2.x.nuspec
Resolves #1028
/cc @davidmrdavid
> Remove duplicate Python Durable Orchestrator

- Functions.Templates/Bindings/bindings.json
- Functions.Templates/Templates/DurableFunctionsActivity-CSharp-2.x/metadata.json
- Functions.Templates/Templates/DurableFunctionsActivity-PowerShell-2.x/metadata.json
- Functions.Templates/Templates/DurableFunctionsActivity-Python-2.x/metadata.json
- Functions.Templates/Templates/DurableFunctionsEntity-JavaScript/metadata.json
- Functions.Templates/Templates/DurableFunctionsEntity-Python-2.x/metadata.json
- Functions.Templates/Templates/DurableFunctionsEntity-TypeScript/metadata.json
- Functions.Templates/Templates/DurableFunctionsEntityClass-CSharp-2.x/metadata.json
- Functions.Templates/Templates/DurableFunctionsEntityFunction-CSharp-2.x/metadata.json
- Functions.Templates/Templates/DurableFunctionsEntityHttp-CSharp-2.x/.template.config/template.json
- Functions.Templates/Templates/DurableFunctionsEntityHttp-CSharp-2.x/metadata.json
- Functions.Templates/Templates/DurableFunctionsEntityHttpStart-CSharp-2.x/metadata.json
- Functions.Templates/Templates/DurableFunctionsEntityHttpStart-JavaScript/metadata.json
- Functions.Templates/Templates/DurableFunctionsEntityHttpStart-TypeScript/metadata.json
- Functions.Templates/Templates/DurableFunctionsHttpStart-CSharp-2.x/metadata.json
- Functions.Templates/Templates/DurableFunctionsHttpStart-CSharp/metadata.json
- Functions.Templates/Templates/DurableFunctionsHttpStart-PowerShell-2.x/metadata.json
- Functions.Templates/Templates/DurableFunctionsHttpStart-Python-2.x/metadata.json
- Functions.Templates/Templates/DurableFunctionsOrchestration-CSharp-2.x/.template.config/template.json
- Functions.Templates/Templates/DurableFunctionsOrchestration-CSharp-2.x/metadata.json
- Functions.Templates/Templates/DurableFunctionsOrchestrator-CSharp-2.x/metadata.json
- Functions.Templates/Templates/DurableFunctionsOrchestrator-CSharp/metadata.json
- Functions.Templates/Templates/DurableFunctionsOrchestrator-PowerShell-2.x/metadata.json
- Functions.Templates/Templates/DurableFunctionsOrchestrator-Python-2.x/metadata.json
Updated `Microsoft.Azure.WebJobs.Extensions.DurableTask` version from 2.4.2 to 2.4.3.
> Update DurableTask version to 2.4.3

- Functions.Templates/Resources_lcl/cs-CZ/Resources.resx.lcl
- Functions.Templates/Resources_lcl/de-DE/Resources.resx.lcl
- Functions.Templates/Resources_lcl/es-ES/Resources.resx.lcl
- Functions.Templates/Resources_lcl/fr-FR/Resources.resx.lcl
- Functions.Templates/Resources_lcl/hu-HU/Resources.resx.lcl
- Functions.Templates/Resources_lcl/it-IT/Resources.resx.lcl
- Functions.Templates/Resources_lcl/ja-JP/Resources.resx.lcl
- Functions.Templates/Resources_lcl/ko-KR/Resources.resx.lcl
- Functions.Templates/Resources_lcl/nl-NL/Resources.resx.lcl
- Functions.Templates/Resources_lcl/pl-PL/Resources.resx.lcl
- Functions.Templates/Resources_lcl/pt-BR/Resources.resx.lcl
- Functions.Templates/Resources_lcl/pt-PT/Resources.resx.lcl
- Functions.Templates/Resources_lcl/ru-RU/Resources.resx.lcl
- Functions.Templates/Resources_lcl/sv-SE/Resources.resx.lcl
- Functions.Templates/Resources_lcl/tr-TR/Resources.resx.lcl
- Functions.Templates/Resources_lcl/zh-CN/Resources.resx.lcl
- Functions.Templates/Resources_lcl/zh-TW/Resources.resx.lcl
LEGO: Pull request from lego/csigs/hb_e254b079-cf7b-4b0a-8749-95eb27e57c25_20210403121445672 to dev with localized lcls
> LEGO: Pull request from lego/csigs/hb_e254b079-cf7b-4b0a-8749-95eb27e57c25_20210403121445672 to dev

- README.md
Provides more information so #1054 can be closed for now.
> Adding note that the build only works on Windows

- Functions.Templates/Templates/QueueTrigger-PowerShell/run.ps1
- azure-pipelines.yml
Resolves https://github.com/Azure/azure-functions-templates/issues/983
> Remove [string] from $QueueItem in QueueTrigger-PowerShell template

- Functions.Templates/Bindings/bindings.json
- Functions.Templates/Templates/DurableFunctionsActivity-CSharp-2.x/metadata.json
- Functions.Templates/Templates/DurableFunctionsActivity-PowerShell-2.x/metadata.json
- Functions.Templates/Templates/DurableFunctionsActivity-Python-2.x/metadata.json
- Functions.Templates/Templates/DurableFunctionsEntity-JavaScript/metadata.json
- Functions.Templates/Templates/DurableFunctionsEntity-Python-2.x/metadata.json
- Functions.Templates/Templates/DurableFunctionsEntity-TypeScript/metadata.json
- Functions.Templates/Templates/DurableFunctionsEntityClass-CSharp-2.x/metadata.json
- Functions.Templates/Templates/DurableFunctionsEntityFunction-CSharp-2.x/metadata.json
- Functions.Templates/Templates/DurableFunctionsEntityHttp-CSharp-2.x/.template.config/template.json
- Functions.Templates/Templates/DurableFunctionsEntityHttp-CSharp-2.x/metadata.json
- Functions.Templates/Templates/DurableFunctionsEntityHttpStart-CSharp-2.x/metadata.json
- Functions.Templates/Templates/DurableFunctionsEntityHttpStart-JavaScript/metadata.json
- Functions.Templates/Templates/DurableFunctionsEntityHttpStart-TypeScript/metadata.json
- Functions.Templates/Templates/DurableFunctionsHttpStart-CSharp-2.x/metadata.json
- Functions.Templates/Templates/DurableFunctionsHttpStart-CSharp/metadata.json
- Functions.Templates/Templates/DurableFunctionsHttpStart-PowerShell-2.x/metadata.json
- Functions.Templates/Templates/DurableFunctionsHttpStart-Python-2.x/metadata.json
- Functions.Templates/Templates/DurableFunctionsOrchestration-CSharp-2.x/.template.config/template.json
- Functions.Templates/Templates/DurableFunctionsOrchestration-CSharp-2.x/metadata.json
- Functions.Templates/Templates/DurableFunctionsOrchestrator-CSharp-2.x/metadata.json
- Functions.Templates/Templates/DurableFunctionsOrchestrator-CSharp/metadata.json
- Functions.Templates/Templates/DurableFunctionsOrchestrator-PowerShell-2.x/metadata.json
- Functions.Templates/Templates/DurableFunctionsOrchestrator-Python-2.x/metadata.json
Updated `Microsoft.Azure.WebJobs.Extensions.DurableTask` version to `2.*.*`
> Update DurableTask version to 2.*.*

- Functions.Templates/Templates/DurableFunctionsHttpStart-PowerShell-1.x/run.ps1
- Functions.Templates/Templates/DurableFunctionsHttpStart-PowerShell-2.x/run.ps1
- Functions.Templates/Templates/DurableFunctionsOrchestrator-PowerShell-1.x/run.ps1
- Functions.Templates/Templates/DurableFunctionsOrchestrator-PowerShell-2.x/run.ps1
Resolves https://github.com/Azure/azure-functions-templates/issues/1075
> Rename Durable commands

- Functions.Templates/ProjectTemplate/CSharp-Isolated/Company.FunctionApp.csproj
Updating [ Microsoft.Azure.Functions.Worker](https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker/) from 1.5.3 to 1.6.0, which is the latest since 11/3/2021.
> Updating Microsoft.Azure.Functions.Worker package to 1.6.0 in csharp isolated template

- Functions.Templates/Templates/DurableFunctionsOrchestration-CSharp-2.x/.template.config/template.json
As in title, follow-up to: https://github.com/Azure/azure-functions-templates/pull/1138
> Update DurableTask Extension version to 2.6.0 (v3.x)

- Functions.Templates/Templates/DurableFunctionsOrchestration-CSharp-2.x/.template.config/template.json
As in title, follow-up to: #1138
> Update DurableTask Extension version to 2.6.0 (v4.x)

- Build/gulpfile.js
> Naming fix for v4 preview

- Functions.Templates/Templates/ServiceBusQueueTrigger-CSharp/ServiceBusQueueTriggerCSharp.cs
> Fix service bus trigger code

- Functions.Templates/Resources_lcl/Id-id/Resources.resx.lcl
- Functions.Templates/Resources_lcl/cs-CZ/Resources.resx.lcl
- Functions.Templates/Resources_lcl/es-ES/Resources.resx.lcl
- Functions.Templates/Resources_lcl/hu-HU/Resources.resx.lcl
- Functions.Templates/Resources_lcl/it-IT/Resources.resx.lcl
- Functions.Templates/Resources_lcl/ko-KR/Resources.resx.lcl
- Functions.Templates/Resources_lcl/nl-NL/Resources.resx.lcl
- Functions.Templates/Resources_lcl/pl-PL/Resources.resx.lcl
- Functions.Templates/Resources_lcl/pt-BR/Resources.resx.lcl
- Functions.Templates/Resources_lcl/zh-TW/Resources.resx.lcl
LEGO: Pull request from lego/csigs/hb_e254b079-cf7b-4b0a-8749-95eb27e57c25_20220313013133210 to dev with localized lcls
> LEGO: Pull request from lego/csigs/hb_e254b079-cf7b-4b0a-8749-95eb27e57c25_20220313013133210 to dev

- Functions.Templates/Resources_lcl/de-DE/Resources.resx.lcl
- Functions.Templates/Resources_lcl/fr-FR/Resources.resx.lcl
- Functions.Templates/Resources_lcl/pt-PT/Resources.resx.lcl
- Functions.Templates/Resources_lcl/ru-RU/Resources.resx.lcl
- Functions.Templates/Resources_lcl/sv-SE/Resources.resx.lcl
- Functions.Templates/Resources_lcl/tr-TR/Resources.resx.lcl
- Functions.Templates/Resources_lcl/zh-CN/Resources.resx.lcl
LEGO: Pull request from lego/csigs/hb_e254b079-cf7b-4b0a-8749-95eb27e57c25_20220314003127859 to dev with localized lcls
> LEGO: Pull request from lego/csigs/hb_e254b079-cf7b-4b0a-8749-95eb27e57c25_20220314003127859 to dev

- Functions.Templates/Resources_lcl/ja-JP/Resources.resx.lcl
LEGO: Pull request from lego/csigs/hb_e254b079-cf7b-4b0a-8749-95eb27e57c25_20220315003123764 to dev with localized lcls
> LEGO: Pull request from lego/csigs/hb_e254b079-cf7b-4b0a-8749-95eb27e57c25_20220315003123764 to dev

- Functions.Templates/Templates/DurableFunctionsActivity-PowerShell/metadata.json
- Functions.Templates/Templates/DurableFunctionsHttpStart-PowerShell-1.x/metadata.json
- Functions.Templates/Templates/DurableFunctionsHttpStart-PowerShell-2.x/metadata.json
- Functions.Templates/Templates/DurableFunctionsOrchestrator-PowerShell-1.x/metadata.json
- Functions.Templates/Templates/DurableFunctionsOrchestrator-PowerShell-2.x/metadata.json
As in title. It's a long-overdue change.
resolves https://github.com/microsoft/vscode-azurefunctions/issues/3010
> Remove preview tag from DF PS templates

- Functions.Templates/Bindings/bindings.json
- Functions.Templates/Templates/DurableFunctionsActivity-PowerShell/metadata.json
- Functions.Templates/Templates/DurableFunctionsEntityHttp-CSharp-2.x/.template.config/template.json
A long overdue change: We were updating branches v3 and v4 instead, but we just learned that dev branch is now the source of truth.
> Upgrade DF Extension from 2.5.1 to 2.7.0

- Functions.Templates/Bindings/bindings.json
- Functions.Templates/Templates/DurableFunctionsEntityHttp-CSharp-2.x/.template.config/template.json
- Functions.Templates/Templates/DurableFunctionsOrchestration-CSharp-2.x/.template.config/template.json
As in title, preparing for DF Extension release
> Change DF Extension references to 2.7.1

- Functions.Templates/Resources/Resources.resx
The language doesn't really add anything and this saves us having to make a new string for each language we support
> Make SQL binding descriptions generic

- Build/PackageFiles/ExtensionBundle/ExtensionBundlePreviewTemplates-3.x.nuspec
- Build/PackageFiles/ExtensionBundle/ExtensionBundlePreviewTemplates-4.x.nuspec
- Functions.Templates/Resources/Resources.resx
- Functions.Templates/Templates/SqlInputBinding-JavaScript/function.json
- Functions.Templates/Templates/SqlInputBinding-JavaScript/index.js
- Functions.Templates/Templates/SqlInputBinding-JavaScript/metadata.json
- Functions.Templates/Templates/SqlInputBinding-JavaScript/readme.md
- Functions.Templates/Templates/SqlOutputBinding-JavaScript/function.json
- Functions.Templates/Templates/SqlOutputBinding-JavaScript/index.js
- Functions.Templates/Templates/SqlOutputBinding-JavaScript/metadata.json
- Functions.Templates/Templates/SqlOutputBinding-JavaScript/readme.md
Added JavaScript templates for SQL Input and output Bindings
> add sql JS input and output binding templates

- Functions.Templates/Resources_lcl/es-ES/Resources.resx.lcl
- Functions.Templates/Resources_lcl/pt-PT/Resources.resx.lcl
LEGO: Pull request from lego/csigs/hb_e254b079-cf7b-4b0a-8749-95eb27e57c25_20220515011156570 to dev with localized lcls
> LEGO: Pull request from lego/csigs/hb_e254b079-cf7b-4b0a-8749-95eb27e57c25_20220515011156570 to dev

- Functions.Templates/Resources_lcl/Id-id/Resources.resx.lcl
- Functions.Templates/Resources_lcl/cs-CZ/Resources.resx.lcl
- Functions.Templates/Resources_lcl/de-DE/Resources.resx.lcl
- Functions.Templates/Resources_lcl/fr-FR/Resources.resx.lcl
- Functions.Templates/Resources_lcl/hu-HU/Resources.resx.lcl
- Functions.Templates/Resources_lcl/it-IT/Resources.resx.lcl
- Functions.Templates/Resources_lcl/pl-PL/Resources.resx.lcl
- Functions.Templates/Resources_lcl/pt-BR/Resources.resx.lcl
- Functions.Templates/Resources_lcl/ru-RU/Resources.resx.lcl
- Functions.Templates/Resources_lcl/sv-SE/Resources.resx.lcl
- Functions.Templates/Resources_lcl/tr-TR/Resources.resx.lcl
- Functions.Templates/Resources_lcl/zh-CN/Resources.resx.lcl
- Functions.Templates/Resources_lcl/zh-TW/Resources.resx.lcl
LEGO: Pull request from lego/csigs/hb_e254b079-cf7b-4b0a-8749-95eb27e57c25_20220516010422138 to dev with localized lcls
> LEGO: Pull request from lego/csigs/hb_e254b079-cf7b-4b0a-8749-95eb27e57c25_20220516010422138 to dev

- Functions.Templates/Templates/SqlInputBinding-Python/__init__.py
- Functions.Templates/Templates/SqlOutputBinding-Python/__init__.py
Also update the bundle version to v4 since we specify the v4 host
> Add additional steps to SQL binding templates

- Functions.Templates/Resources_lcl/ja-JP/Resources.resx.lcl
- Functions.Templates/Resources_lcl/ko-KR/Resources.resx.lcl
- Functions.Templates/Resources_lcl/nl-NL/Resources.resx.lcl
LEGO: Pull request from lego/csigs/hb_e254b079-cf7b-4b0a-8749-95eb27e57c25_20220517011844548 to dev with localized lcls
> LEGO: Pull request from lego/csigs/hb_e254b079-cf7b-4b0a-8749-95eb27e57c25_20220517011844548 to dev

- Functions.Templates/Bindings/bindings.json
- Functions.Templates/Templates/DurableFunctionsEntityHttp-CSharp-2.x/.template.config/template.json
- Functions.Templates/Templates/DurableFunctionsOrchestration-CSharp-2.x/.template.config/template.json
> Update DF version to 2.8.1

- Build/PackageFiles/ExtensionBundle/ExtensionBundlePreviewTemplates-3.x.nuspec
- Build/PackageFiles/ExtensionBundle/ExtensionBundlePreviewTemplates-4.x.nuspec
- Functions.Templates/Templates/SqlInputBinding-PowerShell/function.json
- Functions.Templates/Templates/SqlInputBinding-PowerShell/metadata.json
- Functions.Templates/Templates/SqlInputBinding-PowerShell/readme.md
- Functions.Templates/Templates/SqlInputBinding-PowerShell/run.ps1
- Functions.Templates/Templates/SqlOutputBinding-PowerShell/function.json
- Functions.Templates/Templates/SqlOutputBinding-PowerShell/metadata.json
- Functions.Templates/Templates/SqlOutputBinding-PowerShell/readme.md
- Functions.Templates/Templates/SqlOutputBinding-PowerShell/run.ps1
Add SQL PowerShell Input and Output Binding Templates
> Add SQL PowerShell Input and Output Binding Templates

- Functions.Templates/Resources_lcl/Id-id/Resources.resx.lcl
- Functions.Templates/Resources_lcl/cs-CZ/Resources.resx.lcl
- Functions.Templates/Resources_lcl/de-DE/Resources.resx.lcl
- Functions.Templates/Resources_lcl/es-ES/Resources.resx.lcl
- Functions.Templates/Resources_lcl/fr-FR/Resources.resx.lcl
- Functions.Templates/Resources_lcl/hu-HU/Resources.resx.lcl
- Functions.Templates/Resources_lcl/it-IT/Resources.resx.lcl
- Functions.Templates/Resources_lcl/ja-JP/Resources.resx.lcl
- Functions.Templates/Resources_lcl/ko-KR/Resources.resx.lcl
- Functions.Templates/Resources_lcl/nl-NL/Resources.resx.lcl
- Functions.Templates/Resources_lcl/pl-PL/Resources.resx.lcl
- Functions.Templates/Resources_lcl/pt-BR/Resources.resx.lcl
- Functions.Templates/Resources_lcl/pt-PT/Resources.resx.lcl
- Functions.Templates/Resources_lcl/ru-RU/Resources.resx.lcl
- Functions.Templates/Resources_lcl/sv-SE/Resources.resx.lcl
- Functions.Templates/Resources_lcl/tr-TR/Resources.resx.lcl
- Functions.Templates/Resources_lcl/zh-CN/Resources.resx.lcl
- Functions.Templates/Resources_lcl/zh-TW/Resources.resx.lcl
LEGO: Pull request from lego/csigs/hb_e254b079-cf7b-4b0a-8749-95eb27e57c25_20221023003318121 to dev with localized lcls
> LEGO: Pull request from lego/csigs/hb_e254b079-cf7b-4b0a-8749-95eb27e57c25_20221023003318121 to dev

- Functions.Templates/Resources_lcl/nl-NL/Resources.resx.lcl
- Functions.Templates/Resources_lcl/tr-TR/Resources.resx.lcl
- Functions.Templates/Resources_lcl/zh-CN/Resources.resx.lcl
LEGO: Pull request from lego/csigs/hb_e254b079-cf7b-4b0a-8749-95eb27e57c25_20221024003914081 to dev with localized lcls
> LEGO: Pull request from lego/csigs/hb_e254b079-cf7b-4b0a-8749-95eb27e57c25_20221024003914081 to dev

- Functions.Templates/Resources_lcl/ja-JP/Resources.resx.lcl
LEGO: Pull request from lego/csigs/hb_e254b079-cf7b-4b0a-8749-95eb27e57c25_20221025004140710 to dev with localized lcls
> LEGO: Pull request from lego/csigs/hb_e254b079-cf7b-4b0a-8749-95eb27e57c25_20221025004140710 to dev

- Functions.Templates/Resources_lcl/Id-id/Resources.resx.lcl
- Functions.Templates/Resources_lcl/cs-CZ/Resources.resx.lcl
- Functions.Templates/Resources_lcl/de-DE/Resources.resx.lcl
- Functions.Templates/Resources_lcl/es-ES/Resources.resx.lcl
- Functions.Templates/Resources_lcl/fr-FR/Resources.resx.lcl
- Functions.Templates/Resources_lcl/hu-HU/Resources.resx.lcl
- Functions.Templates/Resources_lcl/it-IT/Resources.resx.lcl
- Functions.Templates/Resources_lcl/ja-JP/Resources.resx.lcl
- Functions.Templates/Resources_lcl/ko-KR/Resources.resx.lcl
- Functions.Templates/Resources_lcl/nl-NL/Resources.resx.lcl
- Functions.Templates/Resources_lcl/pl-PL/Resources.resx.lcl
- Functions.Templates/Resources_lcl/pt-BR/Resources.resx.lcl
- Functions.Templates/Resources_lcl/pt-PT/Resources.resx.lcl
- Functions.Templates/Resources_lcl/ru-RU/Resources.resx.lcl
- Functions.Templates/Resources_lcl/sv-SE/Resources.resx.lcl
- Functions.Templates/Resources_lcl/tr-TR/Resources.resx.lcl
- Functions.Templates/Resources_lcl/zh-CN/Resources.resx.lcl
- Functions.Templates/Resources_lcl/zh-TW/Resources.resx.lcl
LEGO: Pull request from lego/csigs/hb_e254b079-cf7b-4b0a-8749-95eb27e57c25_20221103003451331 to dev with localized lcls
> LEGO: Pull request from lego/csigs/hb_e254b079-cf7b-4b0a-8749-95eb27e57c25_20221103003451331 to dev

- Functions.Templates/Resources_lcl/hu-HU/Resources.resx.lcl
- Functions.Templates/Resources_lcl/it-IT/Resources.resx.lcl
- Functions.Templates/Resources_lcl/ja-JP/Resources.resx.lcl
- Functions.Templates/Resources_lcl/nl-NL/Resources.resx.lcl
- Functions.Templates/Resources_lcl/pt-PT/Resources.resx.lcl
- Functions.Templates/Resources_lcl/sv-SE/Resources.resx.lcl
- Functions.Templates/Resources_lcl/tr-TR/Resources.resx.lcl
LEGO: Pull request from lego/csigs/hb_e254b079-cf7b-4b0a-8749-95eb27e57c25_20221104003130497 to dev with localized lcls
> LEGO: Pull request from lego/csigs/hb_e254b079-cf7b-4b0a-8749-95eb27e57c25_20221104003130497 to dev

- Functions.Templates/Bindings/bindings-bundle-v4.json
- Functions.Templates/Bindings/bindings.json
- Functions.Templates/Templates/DurableFunctionsEntityHttp-CSharp-2.x/.template.config/template.json
- Functions.Templates/Templates/DurableFunctionsOrchestration-CSharp-2.x/.template.config/template.json
> Update DF version to 2.9.0

- Functions.Templates/Bindings/bindings-bundle-v4.json
- Functions.Templates/Bindings/bindings.json
- Functions.Templates/Templates/DurableFunctionsEntityHttp-CSharp-2.x/.template.config/template.json
- Functions.Templates/Templates/DurableFunctionsOrchestration-CSharp-2.x/.template.config/template.json
Updated Microsoft.Azure.WebJobs.Extensions.DurableTask version from 2.9.0 to 2.9.1
> Update Microsoft.Azure.WebJobs.Extensions.DurableTask version to 2.9.1

- V2ProgrammingModel/action-schemas.json
- V2ProgrammingModel/examples/TimerTrigger/template.json
> Added actions schema.

- Functions.Templates/Templates/SqlInputBinding-CSharp/.template.config/template.json
- Functions.Templates/Templates/SqlInputBinding-CSharp/SqlInputBindingCSharp.cs
- Functions.Templates/Templates/SqlOutputBinding-CSharp/.template.config/template.json
- Functions.Templates/Templates/SqlOutputBinding-CSharp/SqlOutputBindingCSharp.cs
1. Update connection string attribute changes
2. Update the extension version
> Sql input/output binding template updates

- Docs/Actions/actiontemplate.md
- Docs/template-schema.json
- Functions.Templates/Templates-v2/HttpTrigger-Python/function_app.py
- Functions.Templates/Templates-v2/HttpTrigger-Python/function_body.py
- Functions.Templates/Templates-v2/HttpTrigger-Python/template.json
- Functions.Templates/Templates-v2/TimerTrigger-Python/function_app.py
- Functions.Templates/Templates-v2/TimerTrigger-Python/function_body.py
- Functions.Templates/Templates-v2/TimerTrigger-Python/template.json
* Added action doc template.
* Revised template-schema.json to reflect schema design changes.
* Updated examples to match template schema changes.
> V2 Schema Design Changes

- Docs/action-schemas.json
- Docs/template-schema.json
- Functions.Templates/Templates-v2/HttpTrigger-Python/template.json
- Functions.Templates/Templates-v2/TimerTrigger-Python/template.json
* Added mandatory `replaceTokens` property on `WriteToFile` action.
* Renamed `ReadFromFile` action to `GetTemplateFileContent`.
* Updated conditional logic.
> Schema changes per discussion.

- Functions.Templates/Templates/EventHubTrigger-CSharp-5.x/.template.config/template.json
- Functions.Templates/Templates/EventHubTrigger-FSharp-Isolated/EventHubTriggerFSharp.fs
- Functions.Templates/Templates/EventHubTrigger-FSharp/.template.config/template.json
- Functions.Templates/Templates/EventHubTrigger-FSharp/EventHubTriggerFSharp.fs
The focus of these changes is to update the package version for `Microsoft.Azure.WebJobs.Extensions.EventHubs` to 5.3.0.  Included are some additional tweaks to clean-up code and modernize syntax.
> [Event Hubs] Update package version

- Functions.Templates/ProjectTemplate_v4.x/CSharp-Isolated/Company.FunctionApp.csproj
- Functions.Templates/ProjectTemplate_v4.x/FSharp-Isolated/Company.FunctionApp.fsproj
Update dotnet-isolated templates to use latest worker SDKs.
- https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker/1.14.1
- https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Sdk/1.10.0
> Update dotnet-isolated template to use latest worker SDK(1.14.1, 1.10.0)

- Functions.Templates/ProjectTemplate_v4.x/FSharp/.template.config/template.json
> Fix incorrect casing #1352

- Functions.Templates/Templates/BlobTrigger-CSharp-Isolated/.template.config/template.json
- Functions.Templates/Templates/BlobTrigger-FSharp-Isolated/.template.config/template.json
- Functions.Templates/Templates/CosmosDBTrigger-CSharp-Isolated/.template.config/template.json
- Functions.Templates/Templates/CosmosDBTrigger-CSharp-Isolated/CosmosDBTriggerCSharp.cs
- Functions.Templates/Templates/CosmosDBTrigger-FSharp-Isolated/.template.config/template.json
- Functions.Templates/Templates/CosmosDBTrigger-FSharp-Isolated/CosmosDBTriggerFSharp.fs
- Functions.Templates/Templates/EventGridTrigger-CSharp-Isolated/.template.config/template.json
- Functions.Templates/Templates/EventGridTrigger-FSharp-Isolated/.template.config/template.json
- Functions.Templates/Templates/EventHubTrigger-CSharp-Isolated/.template.config/template.json
- Functions.Templates/Templates/EventHubTrigger-FSharp-Isolated/.template.config/template.json
- Functions.Templates/Templates/QueueTrigger-CSharp-Isolated/.template.config/template.json
- Functions.Templates/Templates/QueueTrigger-FSharp-Isolated/.template.config/template.json
- Functions.Templates/Templates/ServiceBusQueueTrigger-CSharp-Isolated/.template.config/template.json
- Functions.Templates/Templates/ServiceBusTopicTrigger-CSharp-Isolated/.template.config/template.json
Replacing #1423
(but from a branch)
> updating isolated templates to use T2 extensions by default

- Functions.Templates/ProjectTemplate_v3.x/CSharp-Isolated/.template.config/template.json
- Functions.Templates/ProjectTemplate_v3.x/CSharp/.template.config/template.json
- Functions.Templates/ProjectTemplate_v3.x/FSharp/.template.config/template.json
- Functions.Templates/ProjectTemplate_v4.x/CSharp-Isolated/.template.config/template.json
- Functions.Templates/ProjectTemplate_v4.x/CSharp/.template.config/template.json
- Functions.Templates/ProjectTemplate_v4.x/FSharp-Isolated/.template.config/template.json
- Functions.Templates/ProjectTemplate_v4.x/FSharp/.template.config/template.json
VS issue processing existing type, which we don't think is depended upon anywhere, but we should check, hence leaving this draft for now.
> changing AzureWebJobsStorage data type to valid type

- Functions.Templates/Bindings/bindings-bundle-v4.json
- Functions.Templates/Templates/SqlInputBinding-CSharp-Isolated/.template.config/template.json
- Functions.Templates/Templates/SqlInputBinding-CSharp/.template.config/template.json
- Functions.Templates/Templates/SqlOutputBinding-CSharp-Isolated/.template.config/template.json
- Functions.Templates/Templates/SqlOutputBinding-CSharp/.template.config/template.json
- Functions.Templates/Templates/SqlTrigger-CSharp-Isolated/.template.config/template.json
- Functions.Templates/Templates/SqlTrigger-CSharp/.template.config/template.json
Update sql extension to the latest.
> bump SQL extension

- Functions.Templates/ProjectTemplate_v4.x/CSharp-Isolated/Company.FunctionApp.csproj
- Functions.Templates/ProjectTemplate_v4.x/FSharp-Isolated/Company.FunctionApp.fsproj
Updating Microsoft.Azure.Functions.Worker.Sdk to 1.15.0 in dotnet isolated templates.
https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Sdk
> Updating Microsoft.Azure.Functions.Worker.Sdk to 1.15.0 in dni templates

- Functions.Templates/Resources_lcl/cs-CZ/Resources.resx.lcl
- Functions.Templates/Resources_lcl/es-ES/Resources.resx.lcl
- Functions.Templates/Resources_lcl/fr-FR/Resources.resx.lcl
- Functions.Templates/Resources_lcl/it-IT/Resources.resx.lcl
- Functions.Templates/Resources_lcl/ja-JP/Resources.resx.lcl
- Functions.Templates/Resources_lcl/pt-BR/Resources.resx.lcl
- Functions.Templates/Resources_lcl/pt-PT/Resources.resx.lcl
- Functions.Templates/Resources_lcl/ru-RU/Resources.resx.lcl
- Functions.Templates/Resources_lcl/tr-TR/Resources.resx.lcl
- Functions.Templates/Resources_lcl/zh-CN/Resources.resx.lcl
- Functions.Templates/Resources_lcl/zh-TW/Resources.resx.lcl
LEGO: Pull request from lego/csigs/hb_e254b079-cf7b-4b0a-8749-95eb27e57c25_20231001003330411 to dev with localized lcls
> LEGO: Pull request from lego/csigs/hb_e254b079-cf7b-4b0a-8749-95eb27e57c25_20231001003330411 to dev

- Functions.Templates/Resources_lcl/Id-id/Resources.resx.lcl
- Functions.Templates/Resources_lcl/hu-HU/Resources.resx.lcl
- Functions.Templates/Resources_lcl/nl-NL/Resources.resx.lcl
- Functions.Templates/Resources_lcl/pl-PL/Resources.resx.lcl
- Functions.Templates/Resources_lcl/sv-SE/Resources.resx.lcl
LEGO: Pull request from lego/csigs/hb_e254b079-cf7b-4b0a-8749-95eb27e57c25_20231002003253431 to dev with localized lcls
> LEGO: Pull request from lego/csigs/hb_e254b079-cf7b-4b0a-8749-95eb27e57c25_20231002003253431 to dev

- Functions.Templates/Resources_lcl/de-DE/Resources.resx.lcl
- Functions.Templates/Resources_lcl/ko-KR/Resources.resx.lcl
LEGO: Pull request from lego/csigs/hb_e254b079-cf7b-4b0a-8749-95eb27e57c25_20231003003341084 to dev with localized lcls
> LEGO: Pull request from lego/csigs/hb_e254b079-cf7b-4b0a-8749-95eb27e57c25_20231003003341084 to dev

- azure-pipelines.yml
Adding logging to access storage account name.
> Logging account name for debugging

- Functions.Templates/ProjectTemplate_v4.x/CSharp-Isolated/Company.FunctionApp.csproj
- Functions.Templates/ProjectTemplate_v4.x/FSharp-Isolated/Company.FunctionApp.fsproj
Updating Microsoft.Azure.Functions.Worker.Sdk to 1.15.1 (from 1.15.0)
> Updating Microsoft.Azure.Functions.Worker.Sdk to 1.15.1 in dni templates

- Functions.Templates/Bindings/bindings-bundle-v4.json
- Functions.Templates/Bindings/bindings.json
- Functions.Templates/Templates/DurableFunctionsEntityHttp-CSharp-2.x/.template.config/template.json
- Functions.Templates/Templates/DurableFunctionsOrchestration-CSharp-2.x/.template.config/template.json
Routine PR for the new release. Update the version number for Durable Functions since we make the new release.
> Update Durable Functions extension version to v2.12.0

- Functions.Templates/ProjectTemplate_v4.x/CSharp-Isolated/Company.FunctionApp.csproj
- Functions.Templates/ProjectTemplate_v4.x/CSharp-Isolated/Program.cs
Resolves #1424 
Official docs: https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide#application-insights
> Add AppInsights to dotnet-isolated template

- Functions.Templates/ProjectTemplate_v4.x/FSharp-Isolated/Company.FunctionApp.fsproj
- Functions.Templates/ProjectTemplate_v4.x/FSharp-Isolated/Program.fs
Official docs: https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide#application-insights
> Add app insights to FSharp template

- Functions.Templates/ProjectTemplate_v4.x/CSharp-Isolated/Company.FunctionApp.csproj
- Functions.Templates/ProjectTemplate_v4.x/FSharp-Isolated/Company.FunctionApp.fsproj
Updating Microsoft.Azure.Functions.Worker.Sdk to 1.16.1 (from 1.15.1)
> Updating Microsoft.Azure.Functions.Worker.Sdk to 1.16.0 in dni templates

- Functions.Templates/ProjectTemplate_v4.x/CSharp-Isolated/Company.FunctionApp.csproj
- Functions.Templates/ProjectTemplate_v4.x/FSharp-Isolated/Company.FunctionApp.fsproj
Updating worker package to 1.20.0 and worker.sdk to 1.16.1
> Updating worker package to 1.20.0 and worker.sdk to 1.16.1

- Functions.Templates/ProjectTemplate_v4.x/CSharp-Isolated/Company.FunctionApp.csproj
- Functions.Templates/ProjectTemplate_v4.x/FSharp-Isolated/Company.FunctionApp.fsproj
Update DNI templates to use Worker.Sdk version 1.16.3
https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Sdk/1.16.3
> Update DNI templates to use Worker.Sdk version 1.16.3

- Functions.Templates/ProjectTemplate_v4.x/CSharp-Isolated/Company.FunctionApp.csproj
- Functions.Templates/ProjectTemplate_v4.x/FSharp-Isolated/.template.config/template.json
- Functions.Templates/ProjectTemplate_v4.x/FSharp-Isolated/Company.FunctionApp.fsproj
resolves #1483 
- Added Framework reference to ASP.NET Core (unless .NET Framework)
- Verified and updated nuget packages to the latest versions
- Updated both csharp and fsharp templates
> Updating project templates for isolated worker model to use latest recommendations

- Functions.Templates/Bindings/bindings-bundle-v4.json
- Functions.Templates/Templates/SqlInputBinding-CSharp-Isolated/.template.config/template.json
- Functions.Templates/Templates/SqlInputBinding-CSharp/.template.config/template.json
- Functions.Templates/Templates/SqlOutputBinding-CSharp-Isolated/.template.config/template.json
- Functions.Templates/Templates/SqlOutputBinding-CSharp/.template.config/template.json
- Functions.Templates/Templates/SqlTrigger-CSharp-Isolated/.template.config/template.json
- Functions.Templates/Templates/SqlTrigger-CSharp/.template.config/template.json
Update SQL Extension version to latest.
> vbump to use sql extension with mds bump

- Functions.Templates/ProjectTemplate_v4.x/CSharp-Isolated/.template.config/template.json
- Functions.Templates/ProjectTemplate_v4.x/FSharp-Isolated/.template.config/template.json
Add net9 to dotnet isolated project templates config.
> Add net9 to dotnet isolated project templates config

- Functions.Templates/ProjectTemplate_v4.x/CSharp-Isolated/Company.FunctionApp.csproj
- Functions.Templates/ProjectTemplate_v4.x/FSharp-Isolated/Company.FunctionApp.fsproj
- Microsoft.Azure.Functions.Worker to 1.22.0
- Microsoft.Azure.Functions.Worker.Sdk to 1.17.4
> Updating Microsoft.Azure.Functions.Worker to 1.22.0 and Worker.sdk to 1.17.4 in DNI templates
